### ISSUE TITLE
GOPATH not set

### ISSUE THREAD

**Issue by pharrisee** [uadmin/uadmin#1]
If using an out-of-the-box go installation it is optional whether you set GOPATH or not.  If you choose not to set GOPATH then go uses a predetermined GOPATH of  $HOME/go (or the equivalent on WIndows).  

See https://github.com/golang/go/wiki/SettingGOPATH.

uadmin presumably tries to get GOPATH by looking for an env var with that name which may not exist.

This causes 'uadmin prepare' to fail saying that GOPATH is not set.

**Comment by uadmin** [comment]
Yes we use GOPATH environment variable for the command-line tool:
https://github.com/uadmin/uadmin/blob/master/cmd/uadmin/main.go#L107

I just checked the document you sent and it says:

> If no GOPATH is set, it is assumed to be $HOME/go on Unix systems and %USERPROFILE%\go on Windows.

I'll change the code to check if the `GOPATH` environment variable exists and if it does not, it will just use the default path as per the golang documentation.

Thank you for reporting and I'll let you know once I push this.

**Comment by uadmin** [comment]
I fixed it and improved the command line tool to show the correct path separator and give a more informative message when updating using `uadmin prepare`
5a2b44bf3359149ad230a30df7a2f4e60991cdc9 a2215e26b0257d7508c34a4e67345cf46f3005c0 4a80eab9c182b55ceda7d806ebda3105d2ac156b ea9f4ec61b9d80099624a0fde967375d6f45d013 c082a4cbdcc0c24068600ea3aeecdfb95d420ad3

**Comment by uadmin** [comment]
@pharrisee I close the issue after testing locally on both Windows and Linux. If you are having any trouble please let me know and I'll reopen this issue.
