### ISSUE TITLE
uadmin.io has no links to the medium tutorials!

### ISSUE THREAD

**Issue by davidhtims** [uadmin/uadmin#10]
It would be nice to point people to https://uadmin.io but most of the links are broken. It especially needs a link to the excellent Medium articles; on the page, not in a menu.

Setup a website repository? I could help then.

**Comment by dxlvgcw** [comment]
As far as I know, uadmin website is still under development.

**Comment by Spotlight64** [comment]
Thanks for reporting. The website right now is under development stage. We will fix this as soon as possible and provide the source links on the page.

**Comment by uadmin** [comment]
We are making a new website #66

**Comment by uadmin** [comment]
We are making a new website #66
