### ISSUE TITLE
package github.com/uadmin/uadmin: exit status 128

### ISSUE THREAD

**Issue by CharleGutierrez** [uadmin/uadmin#11]
go get -u github.com/uadmin/uadmin/...
# cd /home/parallels/go/src/github.com/uadmin/uadmin; git submodule update --init --recursive
fatal: No url found for submodule path 'sample_project/todo' in .gitmodules
package github.com/uadmin/uadmin: exit status 128

<--- when installing udamin i'll get this messages :-<

**Comment by Spotlight64** [comment]
Yes it's because there is .git folder that was left inside the 'sample_project/todo' path which caused the problem. We will remove that one on the next update.

Thanks for reporting.

**Comment by sgoroshko** [comment]
I have same issue

**Comment by Spotlight64** [comment]
Can you show me the error message displayed when you run 'uadmin prepare'?

**Comment by dxlvgcw** [comment]
I also have the same issue. I tried updating my uadmin with go install command and it still shows me 0.1.0.

**Comment by Spotlight64** [comment]
Ok can you please provide the information that you set on the environment variables?

**Comment by dxlvgcw** [comment]
I follow these steps https://uadmin.readthedocs.io/en/latest/_static/install/Windows%20Installation.pdf and nothing is missing on my configuration.

**Comment by Spotlight64** [comment]
Can you please try changing the value of the GOPATH same as the GOROOT that is C:\Go and let me know if it works for you?

**Comment by dxlvgcw** [comment]
I changed it. Nothing happens

**Comment by Spotlight64** [comment]
Did you try this:
$ cd ~/go/src/github.com/uadmin/uadmin/cmd/uadmin
$ go install
$ uadmin version

**Comment by dxlvgcw** [comment]
Yes. Still same issue

**Comment by Spotlight64** [comment]
Ok can you go to Go/bin and let me know if there is an existing uadmin.exe inside that path? If it is, can you provide the date when that file was modified?

**Comment by dxlvgcw** [comment]
I see uadmin.exe. The date modified is 5/2/2019 8:32 AM.

**Comment by Spotlight64** [comment]
I think your problem is uadmin.exe is updating on the go-work/bin path. Try to install uadmin again by running this command: go get -u github.com/uadmin/uadmin/...

Afterwards, apply this procedure again and let me know the result:
$ cd ~/go/src/github.com/uadmin/uadmin/cmd/uadmin
$ go install
$ uadmin version

**Comment by dxlvgcw** [comment]
When I perform go install, I get this error.
warning: GOPATH set to GOROOT (C:\Go) has no effect
..\..\auth.go:13:2: cannot find package "golang.org/x/crypto/bcrypt" in any of:
        C:\Go\src\golang.org\x\crypto\bcrypt (from $GOROOT)
        ($GOPATH not set. For more details see: 'go help gopath')

**Comment by Spotlight64** [comment]
All right. Change the GOPATH variable back to C:\Users\(yourPCname)\go-work in the environment variables then restart your command prompt.

Afterwards, apply this procedure again and let me know the result:
$ cd ~/go/src/github.com/uadmin/uadmin/cmd/uadmin
$ go install
$ uadmin version

**Comment by dxlvgcw** [comment]
It is working now. Thanks!

**Comment by dxlvgcw** [comment]
I got error when I prepare uadmin project.
[   OK   ]   Created: C:\Go\src\github.com\dxlvgcw\aviation\models
[   OK   ]   Created: C:\Go\src\github.com\dxlvgcw\aviation\api
[   OK   ]   Created: C:\Go\src\github.com\dxlvgcw\aviation\views
[   OK   ]   Created: C:\Go\src\github.com\dxlvgcw\aviation\media
[   OK   ]   Created: C:\Go\src\github.com\dxlvgcw\aviation\handlers
[ WARNING]   Unable to copy "static" folder: CreateFile C:\Users\Jensen-pc\go-work\src\github.com\uadmin\uadmin\static: The system cannot find the path specified.
[ WARNING]   Unable to copy "templates" folder: CreateFile C:\Users\Jensen-pc\go-work\src\github.com\uadmin\uadmin\templates: The system cannot find the path specified.

**Comment by Spotlight64** [comment]
Make sure you have a copy folder of uadmin package in the go-work/src/github.com path. In order to do that, go to Go/src/github.com, copy the uadmin package there and paste it in the go-work/src/github.com path.

**Comment by dxlvgcw** [comment]
Great, thanks!

**Comment by Spotlight64** [comment]
You're welcome.

**Comment by sgoroshko** [comment]
docker run --rm -it alpine:3.10 sh
/ # apk update && apk add git go
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/x86_64/APKINDEX.tar.gz
v3.10.0-1-gbcc49b4c70 [http://dl-cdn.alpinelinux.org/alpine/v3.10/main]
v3.10.0-2-gdf3d886d1e [http://dl-cdn.alpinelinux.org/alpine/v3.10/community]
OK: 10327 distinct packages available
(1/17) Installing ca-certificates (20190108-r0)
(2/17) Installing nghttp2-libs (1.38.0-r0)
(3/17) Installing libcurl (7.65.1-r0)
(4/17) Installing expat (2.2.6-r0)
(5/17) Installing pcre2 (10.33-r0)
(6/17) Installing git (2.22.0-r0)
(7/17) Installing binutils (2.32-r0)
(8/17) Installing gmp (6.1.2-r1)
(9/17) Installing isl (0.18-r0)
(10/17) Installing libgomp (8.3.0-r0)
(11/17) Installing libatomic (8.3.0-r0)
(12/17) Installing libgcc (8.3.0-r0)
(13/17) Installing mpfr3 (3.1.5-r1)
(14/17) Installing mpc1 (1.1.0-r0)
(15/17) Installing libstdc++ (8.3.0-r0)
(16/17) Installing gcc (8.3.0-r0)
(17/17) Installing go (1.12.6-r0)
Executing busybox-1.30.1-r2.trigger
Executing ca-certificates-20190108-r0.trigger
OK: 396 MiB in 31 packages
/ # go version
go version go1.12.6 linux/amd64
/ # export GOPATH=/go
/ # export GOROOT=/usr/lib/go
/ # export PATH=$PATH:$GOPATH/bin
/ # env
HOSTNAME=6ad3a65ac644
SHLVL=1
HOME=/root
GOROOT=/usr/lib/go
TERM=xterm
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/go/bin
GOPATH=/go
PWD=/
/ # go get -u github.com/uadmin/uadmin/...
# cd /go/src/github.com/uadmin/uadmin; git submodule update --init --recursive
fatal: No url found for submodule path 'sample_project/todo' in .gitmodules
package github.com/uadmin/uadmin/...: exit status 128
/ # uadmin
sh: uadmin: not found
/ # ls -lah /go/
total 12K    
drwxr-xr-x    3 root     root        4.0K Jun 23 01:21 .
drwxr-xr-x    1 root     root        4.0K Jun 23 01:21 ..
drwxr-xr-x    3 root     root        4.0K Jun 23 01:21 src
/ # ls -lah /go/src/github.com/
total 12K    
drwxr-xr-x    3 root     root        4.0K Jun 23 01:21 .
drwxr-xr-x    3 root     root        4.0K Jun 23 01:21 ..
drwxr-xr-x    3 root     root        4.0K Jun 23 01:21 uadmin

it's do not installed uadmin and his deps

**Comment by sgoroshko** [comment]
/ # cd /go/src/github.com/uadmin/uadmin/cmd/uadmin/
/go/src/github.com/uadmin/uadmin/cmd/uadmin # go install
../../api_handler.go:9:2: cannot find package "github.com/jinzhu/gorm" in any of:
	/usr/lib/go/src/github.com/jinzhu/gorm (from $GOROOT)
	/go/src/github.com/jinzhu/gorm (from $GOPATH)
../../db.go:13:2: cannot find package "github.com/jinzhu/gorm/dialects/mysql" in any of:
	/usr/lib/go/src/github.com/jinzhu/gorm/dialects/mysql (from $GOROOT)
	/go/src/github.com/jinzhu/gorm/dialects/mysql (from $GOPATH)
../../db.go:17:2: cannot find package "github.com/jinzhu/gorm/dialects/sqlite" in any of:
	/usr/lib/go/src/github.com/jinzhu/gorm/dialects/sqlite (from $GOROOT)
	/go/src/github.com/jinzhu/gorm/dialects/sqlite (from $GOPATH)
../../register.go:12:2: cannot find package "github.com/jinzhu/inflection" in any of:
	/usr/lib/go/src/github.com/jinzhu/inflection (from $GOROOT)
	/go/src/github.com/jinzhu/inflection (from $GOPATH)
../../process_upload.go:14:2: cannot find package "github.com/nfnt/resize" in any of:
	/usr/lib/go/src/github.com/nfnt/resize (from $GOROOT)
	/go/src/github.com/nfnt/resize (from $GOPATH)
../../otp.go:9:2: cannot find package "github.com/pquerna/otp" in any of:
	/usr/lib/go/src/github.com/pquerna/otp (from $GOROOT)
	/go/src/github.com/pquerna/otp (from $GOPATH)
../../otp.go:10:2: cannot find package "github.com/pquerna/otp/totp" in any of:
	/usr/lib/go/src/github.com/pquerna/otp/totp (from $GOROOT)
	/go/src/github.com/pquerna/otp/totp (from $GOPATH)
../../export.go:11:2: cannot find package "github.com/tealeg/xlsx" in any of:
	/usr/lib/go/src/github.com/tealeg/xlsx (from $GOROOT)
	/go/src/github.com/tealeg/xlsx (from $GOPATH)
../../auth.go:13:2: cannot find package "golang.org/x/crypto/bcrypt" in any of:
	/usr/lib/go/src/golang.org/x/crypto/bcrypt (from $GOROOT)
	/go/src/golang.org/x/crypto/bcrypt (from $GOPATH)

**Comment by Spotlight64** [comment]
All right. Go to go/bin path and ensure if uadmin file is existing inside it.

![Untitled](https://user-images.githubusercontent.com/49872771/59971100-263bac00-95a8-11e9-872b-4f9e652f66b9.png)

Regarding the dependencies, the other way around is to install those packages manually by typing these commands:
$ go get github.com/jinzhu/gorm
$ go get github.com/jinzhu/gorm/dialects/mysql
$ go get github.com/jinzhu/gorm/dialects/sqlite
$ go get github.com/jinzhu/inflection
$ go get github.com/nfnt/resize
$ go get github.com/pquerna/otp
$ go get github.com/tealeg/xlsx
$ go get golang.org/x/crypto/bcrypt

**Comment by sgoroshko** [comment]
uadmin in $GOPATH/bin - don't created!
it's because cmd "go get ..." getting error and process was interrupted

**Comment by Spotlight64** [comment]
Try to install dependencies first manually:
$ go get github.com/jinzhu/gorm
$ go get github.com/jinzhu/gorm/dialects/mysql
$ go get github.com/jinzhu/gorm/dialects/sqlite
$ go get github.com/jinzhu/inflection
$ go get github.com/nfnt/resize
$ go get github.com/pquerna/otp
$ go get github.com/pquerna/otp/totp
$ go get github.com/tealeg/xlsx
$ go get "golang.org/x/crypto/bcrypt

Afterwards, apply this procedure then let me know the result:
$ cd ~/go/src/github.com/uadmin/uadmin/cmd/uadmin
$ go install
$ uadmin version

**Comment by Spotlight64** [comment]
Otherwise, it has something to do with submodule update --init --recursive error. We will fix this as soon as possible then I'll let you know the update.

Thanks for reporting.

**Comment by Spotlight64** [comment]
Git submodule error fixed in version 0.2.2. Install uAdmin now by running this command:
$ go get -u github.com/uadmin/uadmin/...
