### ISSUE TITLE
update filter does work, thx

### ISSUE THREAD

**Issue by freeairy** [uadmin/uadmin#12]
UI foreign key fields sort but it no works.

**Comment by uadmin** [comment]
Please run `uadmin version` and make sure you have version 0.3.0

Then also use `uadmin prepapre` inside your project to pull the latest version of templates and static files.

**Comment by freeairy** [comment]
[  INFO  ]   0.3.0
There is a confirmed version and the files are updated. thx

01.
https://drive.google.com/file/d/1uxkk5TmFNrCUeKFLBV0c0pkBv6Ad-xfr/view?usp=sharing
02
https://drive.google.com/file/d/1H_fmF0batrtRRNz9-XjKEOG6yHafXRum/view?usp=sharing

**Comment by freeairy** [comment]
3. Point the data will disappear
    Types       Types 
    TypesID     uint

https://drive.google.com/file/d/1439sKfRFWfhjwXuiwgrKo4UdxdKjwGjJ/view?usp=sharing

**Comment by uadmin** [comment]
I just reproduced the error locally. Thanks for reporting. I'll fix the bug and push it ASAP.

Thanks for reporting.

**Comment by uadmin** [comment]
Fixed in version 0.3.1. Make sure fo the following:

update uAdmin: `go get -u github.com/uadmin/uadmin/...`

update templates and static files: run this command inside your project folder `uadmin prepare`

If you have any issues please comment and I'll reopen the issue.

**Comment by freeairy** [comment]
filter sort does work, thx

**Comment by uadmin** [comment]
Thanks for the feedback
