### ISSUE TITLE
Colors in trail

### ISSUE THREAD

**Issue by Khryzen** [uadmin/uadmin#127]
Colors in trail not defined when building the application.

Error:

# github.com/uadmin/uadmin
..\..\..\..\pkg\mod\github.com\uadmin\uadmin@v0.9.0\trail.go:27:20: undefined: colors.None

**Comment by TwistedHardware** [comment]
Thank you Khryzen for the report.

I see the bug. It's in Windows. I'll fix it and release it in v0.9.1
