### ISSUE TITLE
Translations      []translation

### ISSUE THREAD

**Issue by LangPham** [uadmin/uadmin#13]
> canot refer to unexported name uadmin.translation
When i try use admin.F for Translations
(tag `uadmin:"multilingual"` only for short text)

**Comment by uadmin** [comment]
Sorry I didn't get what the problem is. Can you send the code of your model.

**Comment by uadmin** [comment]
I think I know what are you talking about. You want to add a model translation:
 - Activate another language
 - Add `uadmin:"multilingual"`
 - It is highly advised to add also `sql:"type:text;"` This will make the field accept more than 255 chars. Multilingual fields are stored as JSON in the DB which might make the field consume more than 255 chars.
 - F.Translations is will load automatically for you from the DB, so you don't have to worry about it.

For an intro about multilingual: https://medium.com/@twistedhardware/uadmin-the-golang-web-framework-4-customizing-dashboard-d96d90792a07?source=friends_link&sk=49f686b8c66d4af83008c4b60903b6ab

For the documentation of `uadmin.Translate` check this: https://uadmin-docs.readthedocs.io/en/latest/api.html#uadmin-translate

PS: If you added `sql:"type:text;"` it will not change the data type in the database if the table is already created. So you can drop the table and run your application again which will recreate the table with the column using the right data type. If you have already data in there and don't want to loose it, you can change the column data type manually. Even if you change the data type manually, make sure you add the tag regardless so the next person using your source code will get their database created with the correct data type.

**Comment by uadmin** [comment]
Sorry for the really late reply. html tag doesn't support multilingual.
