### ISSUE TITLE
Latest uadmin version's MySQL string collation possibly not compatible with version 0.7.4?

### ISSUE THREAD

**Issue by farhansolodev** [uadmin/uadmin#142]
Uadmin version 0.7.4 creates schemas with a character set of utf8, while the latest version has changed that to utf8mb4.

While still using 0.7.4, manually altering a `longtext` column to utf8mb4 character set throws errors like:

`[  ERROR ]   DB error in Save(message). Error 3988: Conversion from collation utf8mb3_general_ci into utf8mb4_0900_ai_ci impossible for parameter`

...and this is on an empty table.

So is this something that I should worry about when upgrading to the latest uadmin version on an existing database?

**Comment by TwistedHardware** [comment]
Hello,

You don't have to worry about that. It will only affect new schema that
create.
