### ISSUE TITLE
Does includelistjs not complete?

### ISSUE THREAD

**Issue by xserve98** [uadmin/uadmin#17]
hello!

[The document](https://uadmin-docs.readthedocs.io/en/latest/api/modelschema.html#example-2-includelistjs)

get_schema Code: [Initialize lists](https://github.com/uadmin/uadmin/blob/master/get_schema.go#L407)
```
s.IncludeFormJS = []string{}
s.IncludeListJS = []string{}
```

Please help me, thank you

**Comment by Spotlight64** [comment]
IncludeFormJS applies to the form view located after you select a record inside the model while IncludeListJS applies to the list view located after you select a model in the uAdmin dashboard. The usage of IncludeFormJS and IncludeListJS is to initialize the URL Path where the Javascript file(s) are located.

Example:
// One file
IncludeFormJS: []string{"/static/js/form.js"}
IncludeListJS: []string{"/static/js/list.js"}

// Multiple files
IncludeFormJS: []string{"/static/js/form.js", "/static/js/form2.js"}
IncludeListJS: []string{"/static/js/list.js", "/static/js/list2.js"}

Based on the documentation (IncludeListJS):
1.) First, you need to create at least 1 record in the model that you want to make it dynamic when the action is triggered (e.g. You want to add a color of the text when you click the first record, etc.).
2.) Once you are done, right click the record that you have just created then select Inspect.
3.) Pick an attribute that you want to use (e.g. "class", "data-id").
4.) Create a Javascript file in the /static/js/ path.
5.) Inside the Javascript file is an action that you want to request in the list view.

Examples:
> You can add a text color to the first record when you click it.
> You can change the record title when you hover your mouse cursor to the first cell.
> You can add a background color in the entire row when the mouse cursor is detected within it.

6.) To apply an action, declare a ModelSchema built-in function in the variable. Specify the name and URL of the model and finally, initialize the URL path in the IncludeListJS field where Javascript file(s) are located.
7.) Test your application.

**Comment by xserve98** [comment]
It has been solved. thank you！

`
        // Model schema configurations
	modelschema := uadmin.ModelSchema{
		Name:      "Todo", // Model name
		ModelName: "todo", // URL

		// Inside the templates/uadmin path, assign the folder name
		// containing form.html and list.html to be called
		FormTheme: "custom",
		ListTheme: "custom",
	}

	// Call the schema of "todo" model
	// modelschema.ModelName = "Todo"
	todo := uadmin.Schema[modelschema.ModelName]

	// Assign the form theme and list theme to the todo model
	todo.FormTheme = modelschema.FormTheme
	todo.ListTheme = modelschema.ListTheme

	**uadmin.Schema[modelschema.ModelName] = todo**
`
