### ISSUE TITLE
Consider multilevel menus？

### ISSUE THREAD

**Issue by xserve98** [uadmin/uadmin#18]
hi,
Consider multilevel menus？

![image](https://user-images.githubusercontent.com/30794291/71780453-7981c300-2ffd-11ea-9f36-1963019326d2.png)

**Comment by TwistedHardware** [comment]
This can be done from the modeling side fairly easy with no drawback on the current design or operations.

By adding a foreign key in the `DashboardMenu` back to itself calling the new field `Parent` this can be implemented easily.

Cc:
@Spotlight64

**Comment by xserve98** [comment]
thank you， Has been resolved
