### ISSUE TITLE
Cost validation from tutorial

### ISSUE THREAD

**Issue by MarErm27** [uadmin/uadmin#20]
Hello!
I use browser FireFox.
I'm doing uAdmin Tutorial Part 5 - Applying uAdmin Tags and m2m
Link: https://uadmin-docs.readthedocs.io/en/latest/tutorial/part5.html
I made this change: 
Cost int `uadmin:"money;pattern:^[0-9]*$;pattern_msg:Your input must be a number.;help:Input numeric characters only in this field."`
1. Added "d" to Cost and pressed button save.
Result:
![image](https://user-images.githubusercontent.com/56219126/72076204-3c237b00-3306-11ea-8bc8-6fa4be0da4b9.png)

2. Deleted d from Cost and pressed button save.
Result:
![image](https://user-images.githubusercontent.com/56219126/72076406-89075180-3306-11ea-85d4-7dd8254319b9.png)
**_Expectations:_**
**2.1. After I deleted "d" from field Cost I want to be able to save.**
**2.2. I don't want to be able to add "d" to field Cost.**
3. I'm able to save only after I reload the page.

**Comment by TwistedHardware** [comment]
Thank you @MarErm27 for reporting this issue.

@Spotlight64 could you please reproduce the issue and check why it is happening.

**Comment by MarErm27** [comment]
Hi! I'm trying to record a price "1.22" and I can't it keeps saying me that it is not a number. 
![image](https://user-images.githubusercontent.com/56219126/75581254-33cffc80-5a7a-11ea-8b9e-223e6562f014.png)
This is indeed not an int type number, but it is a price and I'm doing it as it shown in tutorial
![image](https://user-images.githubusercontent.com/56219126/75581432-814c6980-5a7a-11ea-9b24-571f250c740e.png)
What am I have to change to make this work?

**Comment by MarErm27** [comment]
I've tried to use int64 type for this field, with value 122 but it's not getting recorded. I was going to do things like this:
	r := big.NewRat(12344, 100)
	fmt.Printf("Internal representation %s\n", r.String())
	fmt.Printf("Decimal representation %s\n", r.FloatString(2))

	// dividing by three often would cause problems with monetary values
	r.Mul(r, big.NewRat(1, 3))
	fmt.Printf("Internal representation %s\n", r.String())
	fmt.Printf("Decimal representation %s\n", r.FloatString(2))

**Comment by MarErm27** [comment]
So to make this work I'm just using a string type this is the only way I've foung

**Comment by MarErm27** [comment]
Since I can't use int64(it's just not getting saved), float is not an option so I've tried to use *big.Float.
I've made a new DB and when I'm trying to open a model with a field type *big.Float I got the error below. So... still can't anything better that string type than price in this case. **I was wondering if you have any suggestions about work with currency in uAdmin**

```
2020/03/01 11:18:32 http: panic serving [::1]:54488: reflect: call of reflect.Value.Interface on zero Value
goroutine 137 [running]:

net/http.(*conn).serve.func1(0xc0000fa5a0)
	d:/Go/src/net/http/server.go:1767 +0x150
panic(0xd61d60, 0xc00029b320)
	d:/Go/src/runtime/panic.go:679 +0x1ee
reflect.valueInterface(0x0, 0x0, 0x0, 0x1, 0x0, 0x0)
	d:/Go/src/reflect/value.go:1008 +0x2e7
reflect.Value.Interface(0x0, 0x0, 0x0, 0x0, 0x0)
	d:/Go/src/reflect/value.go:1003 +0x53
github.com/uadmin/uadmin.getFormData(0xdd00a0, 0xc000300540, 0xc000434600, 0xc0003102c0, 0xc000300018, 0xc00005a1a0)
	D:/MyProjects/src/github.com/uadmin/uadmin/get_form_data.go:136 +0x164a
github.com/uadmin/uadmin.formHandler(0xf33c00, 0xc00029a240, 0xc000434600, 0xc0003102c0)
	D:/MyProjects/src/github.com/uadmin/uadmin/form_handler.go:134 +0x1681
github.com/uadmin/uadmin.mainHandler(0xf33c00, 0xc00029a240, 0xc000434600)
	D:/MyProjects/src/github.com/uadmin/uadmin/main_handler.go:79 +0x1036
github.com/uadmin/uadmin.Handler.func1(0xf34200, 0xc0002e62a0, 0xc000434600)
	D:/MyProjects/src/github.com/uadmin/uadmin/handler.go:107 +0x1a5a
net/http.HandlerFunc.ServeHTTP(0xc0001ea170, 0xf34200, 0xc0002e62a0, 0xc000434500)
	d:/Go/src/net/http/server.go:2007 +0x4b
net/http.(*ServeMux).ServeHTTP(0x12e8360, 0xf34200, 0xc0002e62a0, 0xc000434500)
	d:/Go/src/net/http/server.go:2387 +0x1ad
net/http.serverHandler.ServeHTTP(0xc0002e6000, 0xf34200, 0xc0002e62a0, 0xc000434500)
	d:/Go/src/net/http/server.go:2802 +0x216
net/http.(*conn).serve(0xc0000fa5a0, 0xf351c0, 0xc0001c60c0)
	d:/Go/src/net/http/server.go:1890 +0x171d
created by net/http.(*Server).Serve
	d:/Go/src/net/http/server.go:2927 +0x918
```

**Comment by MarErm27** [comment]
@dxlvgcw 
@Spotlight64 
@alphakitchown
@TwistedHardware 
Please, help

**Comment by MarErm27** [comment]
@Spotlight64
Please, help, how to work with currency in uAdmin?

**Comment by MarErm27** [comment]
SOS
