### ISSUE TITLE
Login system tutorial

### ISSUE THREAD

**Issue by dxlvgcw** [uadmin/uadmin#22]
I follow the steps exactly but I see many errors in my command prompt when i am working on my application like login access, html render and many more. What is causing this??

https://uadmin-docs.readthedocs.io/en/latest/login_system/tutorial/part4.html

**Comment by Spotlight64** [comment]
Good day! The login tutorial right now is no longer following the current standard. We'll update it as soon as possible and inform you once it's done.

Thanks for reporting.

**Comment by Spotlight64** [comment]
For now, check the source code so you will see what parameters do you need to input and what is returning it.

**Comment by dxlvgcw** [comment]
im not really expert in go programming. I willing to wait for new tutorial

**Comment by dxlvgcw** [comment]
This is my errors:
views\login.go:26:19: not enough arguments in call to uadmin.RenderHTML                                                         have (http.ResponseWriter, UserContext, string)                                                                         want (http.ResponseWriter, *http.Request, string, interface {}, ...interface {})    

I fixed it after many minutes by this: uadmin.RenderHTML(w, r, "templates/login.html", userContext)

Then I got another error
views\login.go:57:15: cannot use uadmin.Login2FA(r, username, password, otpPass) (type *uadmin.Session) as type *uadmin.User in assignment        

I stuck on this one.

**Comment by Spotlight64** [comment]
Change the login2fa variable from:
login2fa := &uadmin.User{}

To this:
login2fa := &uadmin.Session{}

Then on printing the results, change it from:
uadmin.Trail(uadmin.DEBUG, "Login as: %s", login)

To this:
uadmin.Trail(uadmin.DEBUG, "Login as: %s", login.User)

Finally, you will get an expected result as shown below:
[  DEBUG ]   Login as: System Admin
[  DEBUG ]   OTP: false

In short, uadmin.Login and uadmin.Login2FA now returns the Session key instead of User. In order to do that, call the User method from the session (e.g. session.User).

**Comment by dxlvgcw** [comment]
it works good. but i need to replace most of the code on future tutorial parts

**Comment by dxlvgcw** [comment]
Another question is when is new documentation release?

**Comment by Spotlight64** [comment]
It might take some time to finish the full documentation for version 0.4.0. There are many new features where you can pass data in the built-in API that I need to work on, uAdmin tutorials that follows the current standard, new uAdmin functions with examples, and fixing the UI in uAdmin quizzes for mobile devices.

**Comment by dxlvgcw** [comment]
its okey, take your time. :)

**Comment by Spotlight64** [comment]
Thank you for Your patience. Appreciated
