### ISSUE TITLE
uAdmin Tutorial Part 11 - Accessing an HTML file

### ISSUE THREAD

**Issue by MarErm27** [uadmin/uadmin#23]
File name: todo_view.go
function call is outdated
uadmin.RenderHTML(w, "templates/todo.html", c)
need to be changed to
uadmin.RenderHTML(w, r, "templates/todo.html", c)

Question: here is not necessary 5th parameter "funcs ...interface{}", may I ask what is it for? Very interesting

**Comment by Spotlight64** [comment]
You are right. Thanks for the info and we'll change it on the next documentation update. For the 5th parameter, I'll figure it out how that works on render.

@TwistedHardware

**Comment by Spotlight64** [comment]
RenderHTML function call is now updated. For 5th parameter, Tf is available by default and if you want to add functions to your template, just add them to funcs which will add them to the template with their original function names. If you added anonymous functions, they will be available in your templates as func1, func2 …etc.
