### ISSUE TITLE
uAdmin Tutorial Part 11 - 12 work with .html

### ISSUE THREAD

**Issue by MarErm27** [uadmin/uadmin#25]
Hello!
Thank you for very detailed tutorial. 
I was wondering if I can ask for a help here. I'm trying to implement to uAdmin this little project that contains only two files:
index.html
https://play.golang.org/p/ZePVD23GSGe
main.go
https://play.golang.org/p/3Si83gR04Hg

It looks like this:
![image](https://user-images.githubusercontent.com/56219126/72207177-6d877c80-34a7-11ea-8377-679ebae36290.png)
You can click a button to turn it on or off. My friend helped me with this.

Based on uAdmin Tutorial Part 11 - 12 I've made this files:
1. templates/tokens.html - which is a copy of index.html from above.
https://play.golang.org/p/thVQLf3MGlv
2. views/tokens_view.go
https://play.golang.org/p/MmxV5I91z9q

And made a change to file views/view.go
```
	if strings.HasSuffix(r.URL.Path, "/tokens") {
		TokensHandler(w, r)
		return
	}
```

I go to http://localhost:8080/http_handler/tokens and when I click On or Off it redirects me to http://localhost:8080/ instead of turning it Off or On. Please help, what am I doing wrong?

**Comment by Spotlight64** [comment]
It's because in the templates/tokens.html, the path of your action attribute in the form is /. This will redirect you to that path.
`<form action="/" method="post">`

So in the views/tokens_view.go, you need to create another struct that contains two fields: one for your data which is the Cards and the URL Path.
```
// Context !
type Context struct {
	Data    []smartCard
	URLPath string
}
```

Now your handler will be something like this:
```
// TokensHandler !
func TokensHandler(w http.ResponseWriter, r *http.Request) {
	context := Context{}

	fmt.Printf("Req: %s\n", r.Host)

	value := r.FormValue("id")
	fmt.Println("Got id:", value)

	for i, e := range Cards {
		if e.ID == value {
			fmt.Printf("Switching state for id %s from %t to %t\n", e.ID, e.State, !e.State)
			Cards[i].State = !Cards[i].State
		}
	}

	context.Data = Cards

	// Include this one to get the URL Path and return to your HTML
	context.URLPath = r.URL.Path

	uadmin.RenderHTML(w, r, "templates/tokens.html", context)
}
```

Finally replace the value of the action attribute in the form from / to {{.URLPath}}
```
<!-- Replace the action / to .URLPath -->
<form action="{{.URLPath}}" method="post">
	{{ range .Data }}
	<label> click </label>
	<button style="background-color:{{ if .State }}green{{ else }}red{{ end }};color:white;width:150px;" name="id" value="{{ .ID }}">
		{{if .State }}on{{ else }}off{{ end }}
	</button>
	<label> to {{ if .State }}disable{{ else }}enable{{ end }} card with id: <b>{{ .ID }}</b> and fingerprint <b>{{ .Fingerprint }}</b> </label><br>
	{{ end }}
</form>
```
Now test your application and see if it will work.

**Comment by MarErm27** [comment]
@Spotlight64 Thank you very much! I've made some changes to make it work:
1) Changed r.Host in views/tokens_view.go
```
	context := Context{}
	r.Host += "/http_handler/tokens"
	fmt.Printf("Req: %s\n", r.Host)
```
2) Changed "." in templates/tokens.html
`   {{ range .Data }}`

There is a problem:
I'm not logged in a system:
![image](https://user-images.githubusercontent.com/56219126/72215749-402ee300-3528-11ea-8abe-ba3cd174d8bb.png)

But I have access to http://localhost:8080/http_handler/tokens
![image](https://user-images.githubusercontent.com/56219126/72215759-65bbec80-3528-11ea-9b36-7306d7b051c9.png)

How to make only logged users with access to it to be able to get access to this page?
Another question is how to represent page /http_handler/tokens in uAdmin Dashboard? I want to use this Icon from flaticon.com for this page in a Dashboard:
![image](https://user-images.githubusercontent.com/56219126/72215831-a9632600-3529-11ea-959c-79aec7d5f0f9.png)

**Comment by Spotlight64** [comment]
You need to check if the user is authenticated. This code will restrict access to the user who is not logged in. Place it at the top part of your handler:
```
// TokensHandler !
func TokensHandler(w http.ResponseWriter, r *http.Request) {
	// Check if the user is not logged in
	if uadmin.IsAuthenticated(r) == nil {
		return
	}

	// Your other codes
}
```
To represent Smartcard page in uAdmin dashboard, go to Dashboard Menu and inside it, add a new record with a URL of /http_handler/tokens. Make it sure that the image size is 128x128.

![Untitled](https://user-images.githubusercontent.com/49872771/72216354-af252f80-355a-11ea-8ad2-f9880fc951c1.png)

**Comment by MarErm27** [comment]
How to add top menu bar?
Like here:
![image](https://user-images.githubusercontent.com/56219126/72216615-5e024500-3534-11ea-9c52-161b98b455ef.png)

**Comment by Spotlight64** [comment]
There is no feature yet that will add uAdmin top menu bar in the custom page. As an alternative, you can try to replicate the top menu bar by hardcoding in CSS and Javascript.

**Comment by MarErm27** [comment]
How to make a model that has a type of a Dashboard? 
So it will be like:
uAdmin Dashboard => My Dashboard => models

**Comment by Spotlight64** [comment]
That feature is not yet implemented. Will do some discussion plan about it.

**Comment by madong17** [comment]
@Spotlight64  For clarification, I do have the working top navigation bar in my HTML. What do you mean by "no feature yet in the custom page"?

**Comment by MarErm27** [comment]
I will need to add different types of models. Here are they:
1. Catalogs - set of models that contains items. For example, the way you operate with cars and employers is different. Some kind of subgroups.
2. Enumerations - set of variables that you cannot change. Pretty close to "Drop Down List in a Field" from uAdmin Tutorial Part 4. Catalogs and Documents may contain fields type of Enumeration. 
3. Documents - set of documents. They can do records in registers. Unlike the Catalog where you keep the information about items, Documents is a place where you keep information about what you do with item.
4. Information register. Documents do records in registers. It's close to what said in Document System Tutorial Part 9 - Updating the Document Version, but there you log record entire document. There might be a field in a document that many different documents may need to change. If you have this situation, you need to move this field to a special model that will also have fields: a registrator - a document that made a record in this model and time when the record was made. So each document that contains this field will display the last record of this model.
5. Accumulation register. This may be used for accounting of machine parts. Instead of shoving only last record (this is what Information register does), this register shows change of item status. As example you had 0 of spare wheels of cars. You get 50 for a first record and used 25 as a second record. First record were done by document "Getting spare wheels of cars" and the second were done by document "Use spare wheels of cars". So two different document made records to this model type of Accumulation register and now both documents show that you have 25 spare wheels of cars in the balance. Each record have registrator and time when the record was made.
Here is two custom model types:
1. Reports - a custom model where you show information about many different models, mainly from registers with difficult conditions, highlighting and other.
2. Data processors is a custom model where you search information about about many different models with difficult conditions and highlighting and do multiple changes. If model has internal validation function then you go to it before changes is done.
There is more types of models might be needed and this 7 is most important. Each type of model may contains hundreds of elements and I want to be about to separate them or main dashboard may become very huge. 
Users usually don't need to see Enumerations and Registers so this subDashboards need to be able to be hidden.

**Comment by madong17** [comment]
@Spotlight64 I get what you mean. You are thinking of including a built-in uadmin navigation bar for your own HTMLs. I support that so I will not create my own navigation bar and design it from scratch.

**Comment by MarErm27** [comment]
When I go to http://localhost:8080/http_handler/tokens an unauthorized user I see nothing. How to show to unauthorized user page for authorization and after authorization get them back to  http://localhost:8080/http_handler/tokens? 
![image](https://user-images.githubusercontent.com/56219126/72219823-4ab6a000-355b-11ea-9e01-8a4e5f6c54ac.png)

**Comment by MarErm27** [comment]
@Spotlight64 I've made a redirection to admin page to make users to be able to log in. But I don't know to to bring them back from /admin. 
```
        // Check if the user is not logged in
	if uadmin.IsAuthenticated(r) == nil {
		http.Redirect(w, r, "/admin", http.StatusSeeOther)
		return
	}
```

**Comment by Spotlight64** [comment]
@MarErm27 Yes because nothing is rendered in http://localhost:8080/http_handler/tokens. To show to unauthorized user page for authorization, you may create a custom login HTML page in the templates folder.

The nearest solution would be to follow this tutorial: https://uadmin-docs.readthedocs.io/en/latest/login_system/coverage.html

**Comment by Spotlight64** [comment]
This might not be the perfect solution because the custom user page authorization and uAdmin login authorization are not related to each other at least I found something that works.

views/tokens_view.go

```
package views

import (
	"fmt"
	"net/http"

	"github.com/uadmin/uadmin"
)

// Context !
type Context struct {
	Data    []smartCard
	URLPath string
	User    *uadmin.User
	OTP     bool
	Message string
}

type smartCard struct {
	ID          string
	Fingerprint string
	State       bool
}

// Cards represent smartcards in the system
var Cards = []smartCard{
	smartCard{"123", "abc", true},
	smartCard{"456", "def", false},
	smartCard{"789", "ghi", true},
}

// TokensHandler !
func TokensHandler(w http.ResponseWriter, r *http.Request) {
	// Initialize the User model from uAdmin
	user := uadmin.User{}

	// Initialize the Context struct that we have created
	context := Context{}

	content := ContentFormHandler(w, r, context)

	// Check if the user submits request in HTML form
	if r.Method == "POST" {
		// Check if the value of the request is login
		if r.FormValue("request") == "login" {
			// Create the parameter of "username"
			username := r.FormValue("username")

			// Get the user record where username is the assigned value
			uadmin.Get(&user, "username=?", username)

			// Check if the fetched record is existing in the User model
			if user.ID > 0 {
				// Create the parameters of "password" and "otp_pass"
				password := r.FormValue("password")
				otpPass := r.FormValue("otp_pass")

				// Pass the requested username and password in Login function to
				// return the full name of the User and the boolean value for
				// IsOTPRequired
				login, otp := uadmin.Login(r, username, password)

				// Initialize Login2FA that returns the User
				login2fa := &uadmin.Session{}

				// Check whether the OTP value from Login function is true
				// and the OTP Password is valid
				if otp == true && user.VerifyOTP(otpPass) {
					// Pass the requested username, password, and OTP Password in
					// Login2FA function to return the full name of the User
					login2fa = uadmin.Login2FA(r, username, password, otpPass)
				}

				// Check if the session is fetched from the Login function
				if login != nil || login2fa != nil {
					// Create a cookie named "user_session" with the value of
					// UserID
					usersession := &http.Cookie{
						Name:  "user_session",
						Value: fmt.Sprint(user.ID),
					}

					if otp == true && user.VerifyOTP(otpPass) {
						// Set the "user_session" cookie to the IP Address
						http.SetCookie(w, usersession)

						// Assign the full name of the user and OTP boolean value to the
						// context
						context = Context{
							Data:    content.Data,
							URLPath: content.URLPath,
							User:    &login2fa.User,
							OTP:     otp,
						}

						// Pass the context data object to the HTML file
						uadmin.RenderHTML(w, r, "templates/tokens.html", context)
						return
					}

					if otp == false && otpPass == "" {
						// Set the "user_session" cookie to the IP Address
						http.SetCookie(w, usersession)

						// Assign the full name of the user and OTP boolean value to the
						// context
						context = Context{
							Data:    content.Data,
							URLPath: content.URLPath,
							User:    &login.User,
							OTP:     otp,
						}

						// Pass the context data object to the HTML file
						uadmin.RenderHTML(w, r, "templates/tokens.html", context)
						return
					}
				}
			}
		}

		// Check if the request submitted is logout
		if r.FormValue("request") == "logout" {
			// Assign the message to the Message field of context
			context.Message = "User has logged out."

			// Deletes the cookie
			usersession := &http.Cookie{
				Name:   "user_session",
				Value:  "",
				MaxAge: -1,
			}
			http.SetCookie(w, usersession)

			// Pass the context data object to the HTML file
			uadmin.RenderHTML(w, r, "templates/login.html", context)
			return
		}
	}

	// Read the cookie of "user_session"
	cookie, _ := r.Cookie("user_session")

	// Check if the fetched cookie is existing
	if cookie != nil {
		// Get the user record based on the value of the cookie
		uadmin.Get(&user, "id = ?", cookie.Value)

		// Assign the full name of the user and OTP boolean value to the
		// context
		context = Context{
			Data:    content.Data,
			URLPath: content.URLPath,
			User:    &user,
			OTP:     user.OTPRequired,
		}

		// Pass the context data object to the HTML file
		uadmin.RenderHTML(w, r, "templates/tokens.html", context)
		return
	}

	// Pass the context data object to the HTML file
	uadmin.RenderHTML(w, r, "templates/login.html", context)
	return
}

// ContentFormHandler !
func ContentFormHandler(w http.ResponseWriter, r *http.Request, context Context) Context {
	fmt.Printf("Req: %s\n", r.Host)

	value := r.FormValue("id")
	fmt.Println("Got id:", value)

	for i, e := range Cards {
		if e.ID == value {
			fmt.Printf("Switching state for id %s from %t to %t\n", e.ID, e.State, !e.State)
			Cards[i].State = !Cards[i].State
		}
	}

	context.Data = Cards
	context.URLPath = r.URL.Path

	return context
}
```

templates/login.html

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login Form</title>
</head>
<body>
	<form method="POST">
		<!-- The assigned name attribute is equivalent to r.FormValue in
		Golang while the assigned value attribute is the value of the
		r.FormValue. (e.g. r.FormValue("request") = "login") -->
		<input type="text" name="username" placeholder="Username"><br>
		<input type="password" name="password" placeholder="Password"><br>
		<input type="text" name="otp_pass" placeholder="OTP Password"><br><br>
		<button type="submit" name="request" value="login">Login</button><br>
	</form>
	<p>{{.Message}}</p>
</body>
</html>
```

templates/tokens.html

```
<!DOCTYPE html>​
<html lang="en">

<head>
	<title>USB List</title>​
</head>

<body>
	<h1>Login as {{.User}}
    {{if eq .OTP true}} with {{else}} without {{end}}
		2FA Authentication</h1>

	<form action="{{.URLPath}}" method="post">
		{{ range .Data }}
		<label> click </label>
		<button style="background-color:{{ if .State }}green{{ else }}red{{ end }};color:white;width:150px;" name="id" value="{{ .ID }}">
			{{if .State }}on{{ else }}off{{ end }}
		</button>
		<label> to {{ if .State }}disable{{ else }}enable{{ end }} card with id: <b>{{ .ID }}</b> and fingerprint <b>{{ .Fingerprint }}</b> </label><br>
		{{ end }}
		<br>
		<button type="submit" name="request" value="logout">Logout</button>
	</form>

</body>
</html>
```
