### ISSUE TITLE
Publish not working

### ISSUE THREAD

**Issue by nrdh3g** [uadmin/uadmin#26]
When I do `uadmin publish` command, this happened....
[  ERROR ]   Unable to connect to uadmin server. Post https://publish.uadmin.io/api/push/: x509: certificate has expired or is not yet valid

**Comment by sigma420** [comment]
I have gone beyond this error by ignoring the expired certificate. It then gets stuck at 

[   OK   ]   Compressing [461/461]
[   OK   ]   Your application has been uploaded
[   OK   ]   Application installed successfully
[  ERROR ]   Unable to publish your project Unable to download dependencies
output:() 
error:exec: "runuser": executable file not found in $PATH:

**Comment by Scypto** [comment]
got the same problem. did you fixed it?

**Comment by TwistedHardware** [comment]
publish is completely removed in 0.6.0, instead we are focusing more on containerization in 0.6.0 and a new tutorial will be published on how to use Heroku to host your application for free.
