### ISSUE TITLE
Dashboard is empty

### ISSUE THREAD

**Issue by dxlvgcw** [uadmin/uadmin#27]
I open admin account in my application. all models are gone in my dashboard in sudden! i dont know why this happen. i only have one user

![Untitled](https://user-images.githubusercontent.com/49378523/72207603-a63e4a80-34d5-11ea-96f2-25fc0e8452be.png)

**Comment by Spotlight64** [comment]
Did you disable the Admin access in the System Admin user before you logged out your account? If that's the case, you can do the following to prevent this issue:
1.) Create a new record in the User model as an Admin. Leave it as it is for emergency purposes.
2.) Delete the .salt file in your project folder then rebuild your application. Go to your console then check the username and password that was automatically generated for you.

**Comment by dxlvgcw** [comment]
Thank you @Spotlight64 for response. my problem is resolved.
