### ISSUE TITLE
Mobile view in quiz

### ISSUE THREAD

**Issue by nrdh3g** [uadmin/uadmin#28]
I was answering some uadmin quizzes. The view does not look good here.

![81819509_819075918516635_4059757264620224512_n](https://user-images.githubusercontent.com/59771860/72207939-2cf42700-34d8-11ea-9c64-c38cf667cf8b.png)

**Comment by Spotlight64** [comment]
As of now, the UI for the uAdmin quizzes works on desktop computers. We'll fix it as soon as possible to make it responsive for all devices.

Thanks for reporting.

**Comment by TwistedHardware** [comment]
@Spotlight64 check https://www.katacoda.com

I think we should develop a training course on their platform.
