### ISSUE TITLE
https://uadmin.io/ serving fonts over http

### ISSUE THREAD

**Issue by hyrmn** [uadmin/uadmin#3]
When rendering https://uadmin.io/, a call is made to load a font from `http://fonts.googleapis.com/css?family=Varela`. However, as the uadmin.io is secured with HTTPS, loading is blocked.

I would have submitted a PR but I didn't see the site source anywhere.

Screenshot of the issue below
 
![image](https://user-images.githubusercontent.com/213495/48338634-7348be80-e666-11e8-8e6f-d1b7c4e17113.png)

Otherwise, everything looks very nice. Incredibly interesting project.

**Comment by uadmin** [comment]
Thanks for reporting. The website is severely under developed. We will fix this for now and leave the source of the website in a new repo

**Comment by uadmin** [comment]
We are making a new website #66
