### ISSUE TITLE
Root URL setting

### ISSUE THREAD

**Issue by MarErm27** [uadmin/uadmin#30]
When I change value for my Root URL setting to /Admin page with address http://localhost:8080/ starts to give me 404 error.
![image](https://user-images.githubusercontent.com/56219126/72220760-1ba52c00-3565-11ea-831d-217aa3c017f3.png)
So I add a handler to redirect it to /Admin page.
![image](https://user-images.githubusercontent.com/56219126/72220805-a5ed9000-3565-11ea-9b5c-22e1a693572c.png)
I've changed Root URL setting by advice of @Spotlight64 to make Api tutorial work for me.

Did I did everything right?

**Comment by Spotlight64** [comment]
No need to add the handler. You need to access `http://localhost:8080/admin/` with a slash on the last part. Accessing `http://localhost:8080/admin` without a slash will not work.

**Comment by dxlvgcw** [comment]
@MarErm27 I also have the same problem. You can try this, it works

uadmin.RootURL = "/admin/"
setting := uadmin.Setting{}
uadmin.Update(&setting, "Value", uadmin.RootURL, "code = ?", "uAdmin.RootURL")

@Spotlight64 Is /admin/ and /admin are two different things?

**Comment by Spotlight64** [comment]
Yes. For RootURL, value must have ending slash (e.g. /admin/, not /admin). Otherwise, it will not work.

**Comment by dxlvgcw** [comment]
Can you add compatibility like /admin/ and /admin or even only admin as a same thing just to avoid confusion?

**Comment by Spotlight64** [comment]
Sure! I'll ask the owner about that.

**Comment by MarErm27** [comment]
I still do the `http.HandleFunc("/", http.HandlerFunc(redirectToAdminPage))`
Because when I move to port 8080 and see there 404 aren't feels right. Maybe I don't know something.

**Comment by alphakitchown** [comment]
@dxlvgcw I found another way to update values from Settings. Update function crashes something else but ParseFormValue did not.

@MarErm27 How about this?
```
setting := uadmin.Setting{}
uadmin.Get(&setting, "code = ?", "uAdmin.Port")
setting.ParseFormValue([]string{strconv.Itoa(8080)})
setting.Save()
```

**Comment by MarErm27** [comment]
@alphakitchown 
Just yesterday I've tried to change this particular setting by uAdmin setting interface and it didn't work. I've tried your way to do it and it works like a charm. Thank you for sharing.

**Comment by Spotlight64** [comment]
@alphakitchown Good day! Since you have been doing amazing support on issues, I would like to invite you to our uadmin group. Join here in Gophers Slack https://gophers.slack.com/join/shared_invite/zt-fajz7jh3-2cpkmFU~hQb8d5LmOCnhfQ#/ then join #uadmin channel. Let's work together!
