### ISSUE TITLE
uAdmin Tutorial Part 15 - Wrapping Up Your Application

### ISSUE THREAD

**Issue by MarErm27** [uadmin/uadmin#31]
Link to tutorial: https://uadmin-docs.readthedocs.io/en/latest/tutorial/part15.html
Bug happens in Edge browser, but in Firefox everything is fine.
![image](https://user-images.githubusercontent.com/56219126/72274882-06e89700-363e-11ea-980a-e5d96c6350d2.png)
Log:
[  ERROR ]   processForm.OpenFile. unable to create file. open ./media/images/dashboardmenu_Icon_PoNx074Ess/d:\Users\Marat\Downloads\flash-drive_raw.png: The filename, directory name, or volume label syntax is incorrect.

I go to Dashboard menu and trying to set an icon for a model. 
![image](https://user-images.githubusercontent.com/56219126/72275074-4adb9c00-363e-11ea-9649-05403a19d00a.png)
When I press save it's not becomes saved.
![image](https://user-images.githubusercontent.com/56219126/72275134-634bb680-363e-11ea-8871-bdab3643fccf.png)

**Comment by dxlvgcw** [comment]
@MarErm27 I am having the same problem too. I told @Spotlight64 on different thread, he said the tutorial will update it but might take long. That will cool to add compatibility for browser edge.

**Comment by alphakitchown** [comment]
it's not compatibility problem.. that is a bug because the edge get full path and chrome isn't

**Comment by dxlvgcw** [comment]
Okey now I noticed. Source code needs to be fixed.

**Comment by Spotlight64** [comment]
Hi guys! I think I already found out why you are having issues on uploading a file in the model. Maybe the version of your Microsoft Edge is already too old. Try to update your Microsoft Edge into the latest version and let me know if it will solve your problem.

Thanks for reporting.

**Comment by dxlvgcw** [comment]
You are correct @Spotlight64. My problem has solved after updating my browser. It is just weird that the upload returns a full path.
