### ISSUE TITLE
Document System Tutorial Part 3 - Linking Models (Folders)

### ISSUE THREAD

**Issue by MarErm27** [uadmin/uadmin#32]
Actions:
1. Create two records in folder, Development is a parent of uAdmin. 
![image](https://user-images.githubusercontent.com/56219126/72338518-b6bd1380-36d5-11ea-97b4-6fa3a59ddd0a.png)

2. Go to Development and here you can make a parent to become a child of it's child. What is it made like this for? 
![image](https://user-images.githubusercontent.com/56219126/72338791-46fb5880-36d6-11ea-8d9e-e3d8fd6c7dea.png)

3. Let's try to delete a parent of uAdmin.
![image](https://user-images.githubusercontent.com/56219126/72339534-7d85a300-36d7-11ea-9050-42b5c138fffd.png)

4. Press Confirm Delete and it's done.
![image](https://user-images.githubusercontent.com/56219126/72339607-9d1ccb80-36d7-11ea-862d-89973e8931cd.png)

And uAdmin don't have a parent anymore. **The problem is** we deleted one object of a system, and it's automatically made another object to be changed. For a document system this may cause a lot of problems. I think that it must not to be possible to delete an object if another object has a link to it. Please add a validation func to check if model is used anywhere else and if it is - say that it's not possible to delete it because it is used here, here and there.

**Comment by TwistedHardware** [comment]
Thank you Mar for the report,

Let me explain what is happening here. When you deleted "Development" which only deleted the record "Development". "uAdmin" record is still in the database and the value of "parent_id" is still pointing to the deleted record. In uAdmin when yu delete a record, we never delete it from the database, we only set "delete_at" to a non-null value. That tells uAdmin that the record is deleted. You can "undelete" the Development record by setting "deleted_at" to null value again.

So why are you seeing a difference in "uAdmin" record? The reason for that is when you deleted "Development" uAdmin cannot access it anymore and cannot get the `String()` value of that record. So, "uAdmin" will show an empty string instead.
