### ISSUE TITLE
API Reference - Read the docs

### ISSUE THREAD

**Issue by dxlvgcw** [uadmin/uadmin#33]
Here is what I checked
- uadmin.RootURL
- uadmin.SiteName
- uadmin.Port

I replace the values of them. When I build again, nothing is changed.

**Comment by MarErm27** [comment]
![image](https://user-images.githubusercontent.com/56219126/72342649-fd167080-36dd-11ea-9198-0b88e38140b0.png)
![image](https://user-images.githubusercontent.com/56219126/72342666-0a335f80-36de-11ea-99bc-b99c348fd2df.png)

Here I've changed uadmin.SiteName and it works. Did you did something different? May you show us a main.go file?

**Comment by dxlvgcw** [comment]
My first trial
![Untitled](https://user-images.githubusercontent.com/49378523/72343112-1254c480-3709-11ea-8327-7560d70e1488.png)

I run my application and did work
[   OK   ]   Server Started: http://0.0.0.0:5555

![Untitled](https://user-images.githubusercontent.com/49378523/72343226-53e56f80-3709-11ea-8b14-f3038e55cb2e.png)

Now I changed the values again in main.go, saved my editor
uadmin.Port = 4500
uadmin.RootURL = "/todo/"
uadmin.SiteName = "Todo application"

I run my application again. The port did not change
[   OK   ]   Server Started: http://0.0.0.0:5555 

Browsed http://localhost:4500/todo/ to check if will work. This happened to me
![Untitled](https://user-images.githubusercontent.com/49378523/72343487-f00f7680-3709-11ea-8f87-90e986186e92.png)

But if I go to http://localhost:5555/admin/, it did work without any changes

![Untitled](https://user-images.githubusercontent.com/49378523/72343226-53e56f80-3709-11ea-8b14-f3038e55cb2e.png)

**Comment by alphakitchown** [comment]
right, did not work for me as well. 

what i did is i go to settings then change things there. run your app again it will work

**Comment by dxlvgcw** [comment]
I am now in Settings. What should I change? Default value or value?

**Comment by alphakitchown** [comment]
change the value

**Comment by dxlvgcw** [comment]
Great thanks, then assigning values in code has no effect

**Comment by alphakitchown** [comment]
yes so this is another bug

**Comment by MarErm27** [comment]
I confirm the bug

**Comment by Spotlight64** [comment]
The easier solution is to configure them in the Settings. If you want hard code as a priority, you can try uadmin.Update function to make it work.

```
// Configurations
uadmin.Port = 4500
uadmin.RootURL = "/todo/"
uadmin.SiteName = "Todo application"

// Initialize the Setting
setting := uadmin.Setting{}

// Use update function to apply the assigned value in Settings
uadmin.Update(&setting, "Value", strconv.Itoa(uadmin.Port), "code = ?", "uAdmin.Port")
uadmin.Update(&setting, "Value", uadmin.RootURL, "code = ?", "uAdmin.RootURL")
uadmin.Update(&setting, "Value", uadmin.SiteName, "code = ?", "uAdmin.SiteName")
```

**Comment by dxlvgcw** [comment]
Update works good, thanks

**Comment by Spotlight64** [comment]
Docs updated to version 0.4.0.
https://uadmin-docs.readthedocs.io/en/latest/
