### ISSUE TITLE
uAdmin is beautiful

### ISSUE THREAD

**Issue by MarErm27** [uadmin/uadmin#34]
uAdmin is very beautiful! The same applies to the site https://www.integritynet.biz/. Is that one also was written in GO? Did you used uAdmin for that?

**Comment by Spotlight64** [comment]
Thank you for your compliment! I'm not maintaining that website so maybe one of them will provide accurate answer for you.

**Comment by Spotlight64** [comment]
The one who made the website is @haroldjeshua. uAdmin is not being used but we have plans to use that on a future marketing website.
