### ISSUE TITLE
Pages inside the model

### ISSUE THREAD

**Issue by MarErm27** [uadmin/uadmin#35]
Hello! I have a model that I want to do and it has 50 fields. It's too much to show all of them at once. May I be able to add pages inside the model?

**Comment by dxlvgcw** [comment]
@MarErm27 I am interested to know that too. I changed the value of Page Length in Settings but it works only in the list. It would be nice to have it inside the model form.

**Comment by MarErm27** [comment]
@dxlvgcw I don't want to make a very long page. I think about tabs like this:
![image](https://user-images.githubusercontent.com/56219126/72435391-07ed0600-37af-11ea-9586-58aa7dd9167e.png)

**Comment by dxlvgcw** [comment]
That is awesome idea! Structure is more organized that way

**Comment by alphakitchown** [comment]
maybe you can do an inline approach.. that is how i did in most of work projects

**Comment by dxlvgcw** [comment]
What do you mean by inline approach?

**Comment by alphakitchown** [comment]
lets say you have many fields in your model. split the fields you have to a different model. set the foreign key to the related model then register an inline to main

**Comment by dxlvgcw** [comment]
I am kind of confused. Can you show us example?

**Comment by alphakitchown** [comment]
give me the list of fields you have

**Comment by dxlvgcw** [comment]
I have a model named **Applicants** with the following fields
- First Name
- Middle Name
- Surname
- Gender
- Age
- Address
- Applied for
- Reason
- Course
- School
- Religion
- Marital Status
- Height
- Weight
- Birthday
- Degree
- Seminar
- Certificate
- Language
- Country

**Comment by dxlvgcw** [comment]
I think it is not wise to separate fields because everything is different.

**Comment by alphakitchown** [comment]
i understand your problem. lets suggest the tab implementation to the developers of this repository

**Comment by dxlvgcw** [comment]
Okey, do you have a way to contact them?

**Comment by alphakitchown** [comment]
check CONTRIBUTES file. their emails are there

**Comment by dxlvgcw** [comment]
I saw it, thanks!

**Comment by dxlvgcw** [comment]
Wait, are you one of the contributors of uadmin?

**Comment by alphakitchown** [comment]
no

**Comment by uadmin** [comment]
This can be developed as form set groups (It is not a thing yet). Something like:

```golang

type Item struct {
  uadmin.Model
  Name string `uadmin:"formset:General"`
  Age int `uadmin:"formset:Advanced"`
}
```

This can be rendered later as an accordion or tabs in the UI.

**Comment by TwistedHardware** [comment]
I don't think anyone is willing to implement this feature. It's been stale for over 2 years.
