### ISSUE TITLE
Oversized image in dashboard

### ISSUE THREAD

**Issue by dxlvgcw** [uadmin/uadmin#36]
I know there is a rule that the image size for a model is 128px. Is there a way to auto resize if I upload different image size? Say automatically resized from 512px to 128px?

![Untitled](https://user-images.githubusercontent.com/49378523/72443696-a8f8b280-37e9-11ea-975d-4dea4e2a782d.png)

**Comment by uadmin** [comment]
Auto resizing in coming in the new release :)

**Comment by uadmin** [comment]
Fixed in https://github.com/uadmin/uadmin/releases/tag/v0.5.0
