### ISSUE TITLE
Delete uploaded image

### ISSUE THREAD

**Issue by dxlvgcw** [uadmin/uadmin#37]
I want this image to remove in the dashboard menu or back to default icon but I don't know how

![Untitled](https://user-images.githubusercontent.com/49378523/72445024-0857c200-37ec-11ea-97ce-1ffa4a576be4.png)

**Comment by uadmin** [comment]
We are adding a new feature to remove images from UI and dAPI in version 0.5.0 (scheduled release date August 1st)

**Comment by uadmin** [comment]
Fixed in https://github.com/uadmin/uadmin/releases/tag/v0.5.0
