### ISSUE TITLE
Google App Engine - standard environment V2 aka Go111?

### ISSUE THREAD

**Issue by davidhtims** [uadmin/uadmin#4]
Is uAdmin compatible with the new [Google App Engine standard environment](https://blog.golang.org/appengine-go111)?

**Comment by uadmin** [comment]
I didn't test it. But I read the blog post and I don't see any reason why it would not work. If you plan to test it on Google App Engine please let me know how did it go. Maybe you will have to do the `go get` manually for uadmin (maybe I'm not an expert in Google Cloud):

https://cloud.google.com/appengine/docs/standard/go111/specifying-dependencies

After reading all of that I think you might want to take a look at the built-in free hosting service that comes with uadmin. This blog post explains that:

https://medium.com/p/16ec1db7d4ac

**Comment by uadmin** [comment]
Closed due to no response from OP
