### ISSUE TITLE
Forced OTP authorization usage

### ISSUE THREAD

**Issue by MarErm27** [uadmin/uadmin#40]
Hello!
I was wondering if uAdmin have an option to force all users to use OTP authorization?

**Comment by dxlvgcw** [comment]
Right now, they only have OTP Required where an administrator need to enable them manually per user. It would be nice to have that, good for security

**Comment by MarErm27** [comment]
@dxlvgcw  can users disable it?

**Comment by dxlvgcw** [comment]
If their permission is blocked to user model, no

**Comment by alphakitchown** [comment]
@dxlvgcw what do you think? https://github.com/uadmin/uadmin/issues/42
