### ISSUE TITLE
Password brute force protection

### ISSUE THREAD

**Issue by MarErm27** [uadmin/uadmin#42]
How to limit the number of attempts to enter the incorrect password by user?
How to block a user after five attempts for 15 minutes?

**Comment by alphakitchown** [comment]
if you mean in uadmin login page, i think they don't have that yet..

**Comment by MarErm27** [comment]
I go to http://localhost:8080/
![image](https://user-images.githubusercontent.com/56219126/72666970-0aa66000-3a28-11ea-87af-33e0e4354810.png)

Here I can make many attempts to login as user Admin with a wrong password. Now I can see a problem with my suggestion - if bot is trying to brute force my password and it will cause my account to be blocked then I will never be able to authorization. May it be the reason why developers of uAdmin didn't add this feature?

**Comment by alphakitchown** [comment]
you have a point there.. that is one possible reason. surely there is a way to mitigate the problem for brute force to be added without hassle.

**Comment by dxlvgcw** [comment]
Password brute force protection is applicable only if admin is disabled in the user.

**Comment by alphakitchown** [comment]
@dxlvgcw what if an attacker tries to brute force admin's password?

**Comment by dxlvgcw** [comment]
I do not know too. Let the developers of uAdmin decide what works best ;)

**Comment by alphakitchown** [comment]
maybe block outsider IP addresses and access login page only by few?

**Comment by dxlvgcw** [comment]
That is one way of doing it but how can you block their IP? You never know who accessed your page.

**Comment by uadmin** [comment]
@dxlvgcw you are right. blocking the IP is the way to go. Implementation of this feature is in the new release 0.5.0 (August 1st). You will be able to set maximum failed attempts and block period in the settings page.

**Comment by dxlvgcw** [comment]
Great to hear!

**Comment by uadmin** [comment]
Fixed in https://github.com/uadmin/uadmin/releases/tag/v0.5.0
