### ISSUE TITLE
May I ask for clarification? - Document System Tutorial Part 11

### ISSUE THREAD

**Issue by MarErm27** [uadmin/uadmin#43]
Link to tutorial: https://uadmin-docs.readthedocs.io/en/latest/document_system/tutorial/part11.html
Full Source Code : https://uadmin-docs.readthedocs.io/en/latest/document_system/tutorial/full_code/part11.html

Here are four permission parameters, all are bool type:
Read
Add
Edit
Delete

When we go throght the code we set them again and again according to the different condition. May it cause a situation when we set them in one condition and afterwards reset them to another one and if it may be, will it make first check unnecessary?

In another worlds, may I put "return" after each time we set this parameters? 
Just like here https://play.golang.org/p/ak8aKIvAqSF
Lines 11, 33, 50, 68, 85

Will it make any difference? What do I don't understand?

**Comment by Spotlight64** [comment]
In permission rule, the most priority is the user permission so if you set permission on that, all others will be ignored.
