### ISSUE TITLE
Instant messaging technology for uAdmin

### ISSUE THREAD

**Issue by nrdh3g** [uadmin/uadmin#46]
Can you make a built in instant messaging in uAdmin that if the user logins his account in the admin page, it will show himself as online in the contacts list. It is convenient so that we do not need to use other social media website to contact each other. Something similar to this

![Pidgin_2 0_contact_window](https://user-images.githubusercontent.com/59771860/72990035-69097f00-3e2a-11ea-901c-a215efd61c82.png)

**Comment by uadmin** [comment]
This requires webstockets to keep checking if the user is still has uAdmin's page open, and tracking user activity to show (away) status. I worked with websockets and I can tell you that I'm really not excited about touching that technology ever again (sorry to all websockets fans).

I might be able to do that with only monitoring user activity (every time the user's code is authenticated) and update an in-memory structure to keep the date/time of the last user activity.

Now messaging it self is almost impossible to do without websockets which is not something that I wish to add.

Maybe we should find a way to add third-party plug-ins to uAdmin, something like:
```golang
uadmin.RegisterPrequestHandler(func (*http.Request, http.ResponseWriter) bool
uadmin.RegisterPostquestHandler(func (*http.Request, http.ResponseWriter) bool
```

This allows the user to add any extra functionality to the standard uAdmin UI as a middleware. This way we (or anyone else) can develop a messaging app as a third-party solution that you can add to uAdmin like:

```golang
package main

import (
  "github.com/uadmin/uadmin"
  "github.com/nrdh3g/uadminchat"
)

func main() {
  uadmin.Register()

  // Adding chat plug-in
  uadmin.RegisterPrerequestHandler(uadminchat.PreHandler)
  uadmin.RegisterPostrequestHandler(uadminchat.PostHandler)
  go uadminchat.StartServer()

  uadmin.StartServer()
}
```

I don't think this is what you are looking for but if you are interested in developing something like this, please let me know and I'll be happy to add middleware handlers.

**Comment by nrdh3g** [comment]
I like that idea so that it will be easier for us to develop an application that has messaging feature.
