### ISSUE TITLE
uadmin.WORKING not working in Trail

### ISSUE THREAD

**Issue by dxlvgcw** [uadmin/uadmin#47]
I am using Trail function with the WORKING tag in main.go. I rebuild my application, nothing is showing. Other tags are working anyway. This is my code.
```
func main() {
	uadmin.Trail(uadmin.WORKING, "Running trail")
	uadmin.StartServer()
}
```

**Comment by Spotlight64** [comment]
I just tried to reproduce the same method and did not print as well. We will fix this as soon as possible then I'll let you know the update.

Thanks for reporting.

**Comment by Spotlight64** [comment]
Good day! uadmin.WORKING is a tag that is used for animation. It can be used for something like a progress bar that you can show on your console. For instance:
```
package main

import (
	"time"

	"github.com/uadmin/uadmin"
)

func main() {
	for i := 1; i <= 3; i++ {
		uadmin.Trail(uadmin.WORKING, "%d/3", i)

		// Equivalent to 1 second
		time.Sleep(1000 * time.Millisecond)
	}
	uadmin.Trail(uadmin.OK, "Done!")
}
```
The application will return a result after you wait for 3 seconds.
![Screencast-2020-07-28-132848](https://user-images.githubusercontent.com/49872771/88623108-d696b080-d0d6-11ea-886f-3b9fd32a6896.gif)
