### ISSUE TITLE
Consider adding file attachments in sending emails?

### ISSUE THREAD

**Issue by madong17** [uadmin/uadmin#48]
From documentation https://uadmin-docs.readthedocs.io/en/latest/api.html#uadmin-sendemail

You can set the email that you want to send to, the subject and the body in a function. Can you add another parameter where we can send a file attachment to the receiver?

**Comment by uadmin** [comment]
That sounds like an awesome new feature. I might be able to squeeze this in the next release. I'll let you know (fingers crossed).

**Comment by madong17** [comment]
I look forward into this. Thanks for the response @uadmin. Let me know if there will be limitations to the attachments like file size or supported extensions.

**Comment by uadmin** [comment]
I will have to make the attachments into an array of file paths. I guess I should also add a new setting for the maximum file size or the total aggregate attachments size maybe?

**Comment by madong17** [comment]
I would favor to have file size limitation in the setting. Default value maybe up to 25 MB?

**Comment by uadmin** [comment]
I'm looking at some sample code of doing this and it is not really hard to do. There is one problem in the approach of the snippet that I'm looking at:

https://gist.github.com/guinso/8405a991d8a095b01427b9ea83934d67

It is encoding the files into base64 in memory before sending the email. This will not work with any large files. Let's say we are trying to send a 25MB file. base64 version of the file will be 1.5 * 25 = 37.5BM plus the original file = 25 + 37.5 = 62.5MB plus the actual email. This might be a very heavy load on memory for some implementations and would cause out of memory problems in productions.

I will try to find a way to do this using `io.copy` which uses 1 bytes of memory at a time while it is copying from the source file to the base64 encoder to the email server. This is a three steps copy process and I don't think I could fit this work with good conscious in a version shipping out in 2 days. I will work on it after the release of the new version.

**Comment by TwistedHardware** [comment]
Fixed in [f91e892](https://github.com/uadmin/uadmin/commit/f91e8923cfed99d30ad898d974b6c77122a4a204)
