### ISSUE TITLE
Read the docs update

### ISSUE THREAD

**Issue by dxlvgcw** [uadmin/uadmin#49]
Hello! Any news on read the docs? Because if the update will take long, I think you need to hire more people to accelerate development. This is my reminder because I am using your framework mainly for one of my projects, working in an IT industry.

**Comment by alphakitchown** [comment]
agree with you.... they need more people. and their website is still broken for A YEAR!

**Comment by Spotlight64** [comment]
Good day! We're doing our best to finish the full documentation for version 0.4.0 despite of managing other projects as well. The nearest date of release possible based on the workload that needs to be done from our current progress would be around April 2020 onwards.

**Comment by dxlvgcw** [comment]
Hmmm that really takes us long to wait but it is okey. Is there any update or still similar to read the docs that we are seeing?

**Comment by Spotlight64** [comment]
There are major updates from the last version of ReadTheDocs. Discussion of using AB Tests was done. Rewriting of uAdmin tutorials is currently in progress.

**Comment by dxlvgcw** [comment]
Yes, please do that!!

**Comment by alphakitchown** [comment]
@Spotlight64 do you have updates now?

**Comment by Spotlight64** [comment]
Yes, as promised. Check it out to see the quick demo of our new uAdmin tutorials.

![uadmin docs update](https://user-images.githubusercontent.com/49872771/73544127-78647a00-4473-11ea-90ac-a49abf7da6f8.gif)

**Comment by alphakitchown** [comment]
its cool @Spotlight64

**Comment by madong17** [comment]
Amazing demo especially the last part

**Comment by Spotlight64** [comment]
Thanks guys!

**Comment by alphakitchown** [comment]
@Spotlight64 Whats the update now in the docs?

**Comment by Spotlight64** [comment]
Right now, I'm still in the process of rewriting uAdmin tutorials. Once I get a chance to work full-time on this one, I will be able to deliver updates here much faster.

**Comment by Spotlight64** [comment]
Docs updated to version 0.4.0.
https://uadmin-docs.readthedocs.io/en/latest/

**Comment by dxlvgcw** [comment]
Thank you @Spotlight64 you promised us for this
