### ISSUE TITLE
PostgreSQL Support

### ISSUE THREAD

**Issue by jeasoft** [uadmin/uadmin#5]
Hi everyone. First of all, great project!! I'm a Django/Python fanboy, but I was looking for something like that in Go/Rust, and this project looks promising. 
But now I was wondering if you have any plans to support PostgreSQL.

Thanks!

Jearel

**Comment by Giancarlos** [comment]
Pretty sure the underlying ORM can support it, they just only have the auto setup for MySQL and SQLite from what I gathered perusing the source. I'm not a maintainer, so maybe one of them will have better insight for you.

**Comment by jeasoft** [comment]
> Pretty sure the underlying ORM can support it, they just only have the auto setup for MySQL and SQLite from what I gathered perusing the source. I'm not a maintainer, so maybe one of them will have better insight for you.

Thanks @Giancarlos for your answer, I'll try soon to see what can I do.

**Comment by TwistedHardware** [comment]
There is very little interest for now to add support for PostgreSQL so I think we will delay to a later version.
