### ISSUE TITLE
Request for account recovery method

### ISSUE THREAD

**Issue by madong17** [uadmin/uadmin#50]
There is a chance that I cannot recover my user account in admin page even if I already forgot password because I cannot access my email in a particular email service. Would you consider to add multiple emails or a mobile number for a single user if a primary email assigned on my user account in uAdmin cannot be accessed?

Else, add another method like security question to recover my uadmin account without going to my email.

**Comment by uadmin** [comment]
Hello, thank you for filing this issue. We never had to discuss them before but there is actually a way to do it. It is a last resort kinda thing but it works once you don't have access any more to your project.

1. Rename your `.salt` file to `.salt.bac`
2. Restart your application. That will generate a new `.salt` file and it will also create a recovery admin account with a long complex password.
3. Login to your system using the recovery admin account.

Now there are two paths, If you don't have other users in the system or you are willing to reset everyone's password:
4. Reset the password of your main admin account by typing a new password and saving.
5. Delete the recovery admin account.

The other path is if you have existing users and you don't want to reset everyone's password:
4. Change the email of your admin account to an email that you have access to.
5. Delete `.salt` file
6. Rename `.salt.bac` to `.salt`
7. Restart your application
8. Reset your password using the reset password features from login and you will get the email to the new email address

I know it is not a simple process but it allows us to keep the system as secure as possible. Second email addresses and secret questions tend to be used to penetrate systems and we want to keep your system bullet proof.

If you have further questions, please re-open the ticket.
