### ISSUE TITLE
uAdmin code autocomplete

### ISSUE THREAD

**Issue by nrdh3g** [uadmin/uadmin#51]
Can you make an autocomplete feature that if the uadmin code is a function, it will automatically generate a formatted code in the editor for you. For example, I type the shortcut keyword like utrail. When I press enter, the code will produce the default result in my editor something like uadmin.Trail(uadmin.DEBUG, "%s", "A") so that I do not need to retype it manually.

**Comment by uadmin** [comment]
Depending on the editor and the extension you are using, you could add a snippet. I'm contacting VSCode golang extension team to see if it is possible to do such a thing with them. I'll get back to you once I have a reply.

**Comment by nrdh3g** [comment]
Thank you @uadmin. I am using Visual Studio Code editor to create uadmin projects.

**Comment by uadmin** [comment]
I got a reply from vscode team and they are suggesting that the user uses this approach:
