### ISSUE TITLE
SOS! How to work with currency in uAdmin?

### ISSUE THREAD

**Issue by MarErm27** [uadmin/uadmin#53]
1) I've tried to keep currency in int64 type and calculate everything in cents but int64 valuest can't be saved - bug?
2) I've tried to keep currency in big.Float type - but SQ Lite have  some errors with it.
3) I've tried to keep currency in string type but my code become very difficult to read and to work with.
4) Now I use float64 my code is relatively easy to read but using float64 for currency is a big NO and I must to find another way to work with currency.

May be I just must change SQ Lite to MySQL? Do anyone know how to work with currency in uAdmin? Which way is preferred?

**Comment by MarErm27** [comment]
There is information in description of uAdmin: MySQL Database Support
But I haven't found how to set MySQL to work with uAdmin

**Comment by Spotlight64** [comment]
Here is a step-by-step procedure to set MySQL to work with uAdmin. In the default collation part, you need to set it to UTF-8 to make it work. https://uadmin-docs.readthedocs.io/en/latest/api.html#uadmin-dbsettings

In the new update, instead of initializing uadmin.Database in the main go, you need to create a new file named .database in the main project directory and inside it, set the following like this:
```
{
    "type":     "mysql",
    "name":     "todo",
    "user":     "root",
    "password": "todolist",
    "host":     "127.0.0.1",
    "port":     3306,
}

**Comment by MarErm27** [comment]
@Spotlight64 
It is seems I can't to create a file named ".database" in Windows

![image](https://user-images.githubusercontent.com/56219126/75780683-e64eda80-5d6c-11ea-8033-185403fb5c0f.png)

**Comment by MarErm27** [comment]
Thats okay I've made a file name ".database."
![image](https://user-images.githubusercontent.com/56219126/75780901-45145400-5d6d-11ea-8e2b-7ea5c73ad13b.png)

**Comment by MarErm27** [comment]
Oh my God!
uAdmin made all of the table by itself! Crazy!
Wow!
But I had to make a little change in this file:
{
    "type":     "mysql",
    "name":     "todo",
    "user":     "root",
    "password": "todolist",
    "host":     "127.0.0.1",
    "port":     3306
}

removed "," after 3306

**Comment by madong17** [comment]
That's the problem that I have been experiencing so long and .database gave justice into it. My issue is different anyway.

**Comment by Spotlight64** [comment]
@MarErm27 That's the magic of uAdmin. Glad you appreciate it. Also thanks for the correction

**Comment by alphakitchown** [comment]
@Spotlight64 Will .database support other kinds of databases aside from SQLite and MySQL?

**Comment by Spotlight64** [comment]
I haven't tested them yet. You can try to give it a shot to see the result.

**Comment by alphakitchown** [comment]
Tried on postgresql it does not work, or maybe my configuration is wrong. Structure is same in mysql configuration

**Comment by MarErm27** [comment]
int64 is still not getting saved in MySQL eighter - and it not saying the error just nothing

I've made a model like below but when I've trying to open a model in uAdmin wev interface I got this error: **unsupported Scan, storing driver.Value type []uint8 into type *big.Float**
package models

```
import (
	"math/big"
	"time"

	"github.com/uadmin/uadmin"
)

// Price model ...
type Price struct {
	uadmin.Model
	Name        string
	Cost         big.Float

}
```

**Comment by Spotlight64** [comment]
Instead of using big.Float data type, replace it to float64.

**Comment by MarErm27** [comment]
> @MarErm27 Instead of using big.Float data type, replace it to float64.
> @alphakitchown Thanks for the info.

May I ensure that I got you right, this is how my model have to look like:
package models

import (
	"time"

	"github.com/uadmin/uadmin"
)

// Price model ...
type Price struct {
	uadmin.Model
	Name        string
        Cost         float64 `uadmin:"money"`
}

**Comment by alphakitchown** [comment]
I checked the source code. It still only support sqlite and mysql

**Comment by Spotlight64** [comment]
@MarErm27 Yes, that's the one.
@alphakitchown Yea saw it. I'll ask the owner for PostgreSQL compatibility. Thanks!

**Comment by MarErm27** [comment]
@Spotlight64 
What to do with Scientific notation of float64? I've seen function ParseFormValue, can it work with float64?
May I ensure that you sure that work with currency in float64 type is accurate enough? Have you any uAdmin magic for this?

**Comment by Spotlight64** [comment]
ParseFormValue is used only for Settings model. I haven't tested it yet so I'll work on that soon. Once tested properly, I'll give you my results.

**Comment by Spotlight64** [comment]
Hello! Is this the one that you are trying to work on (saving scientific notation value in form)?
![Untitled](https://user-images.githubusercontent.com/49872771/75968937-25b22e00-5f09-11ea-8889-b646bd278fe4.png)

Or are you trying to save the scientific notation in the code?

I did some tests in Go Playground and the values are accurate enough. The limitation is that float64 will not show a number that is more than 6 decimal places but it did show everything if the exponent is positive.
```
package main

import (
	"fmt"
)

func main() {
	values := []interface{}{2044, "155.32", 48989e-06, 4898.9e-06, 522e-12, 62.123414446e+12}
	for _, v := range values {
		switch v.(type) {
		case float64, float32:
			fmt.Printf("%f\n", v)
		default:
			fmt.Printf("%v\n", v)
		}
	}
}
```
Results:
```
2044
155.32
0.048989
0.004899
0.000000
62123414446000.000000
```

**Comment by MarErm27** [comment]
> Hello! Is this the one that you are trying to work on (saving scientific notation value in form)?
> ![Untitled](https://user-images.githubusercontent.com/49872771/75968937-25b22e00-5f09-11ea-8889-b646bd278fe4.png)
> 
> Or are you trying to save the scientific notation in the code?

I see scientific notation like you show on the screenshot.
I expect currency to look like 2 000.00, but I see scientific notation instead. I wish money tag could solve it.

**Comment by MarErm27** [comment]
https://play.golang.org/p/rs_z2NBwDPI
```
package main

func main() {
	var fl float64
	fl = 0.1 * 0.2
	print(fl)
}
```
It is prints this in scientific notation
+2.000000e-002
which is equal to this 
0.0200000000000000004163336342344337026588618755340576171875
it is not equal to 0.02

@Spotlight64 I was wondering if I may ask, are there are plans to add int64 support to UAdmin? Are there are plans to add a special money type for work with currency to UAdmin?

**Comment by Spotlight64** [comment]
Sure! I'll ask the owner about that.

**Comment by MarErm27** [comment]
> Sure! I'll ask the owner about that.

@Spotlight64 I was wondering if there are any new information appeared?

**Comment by Spotlight64** [comment]
No new information yet. For now, I'll tag this issue as "Help Wanted".

**Comment by alphakitchown** [comment]
@MarErm27 Try this
```
func (p *Price) Save() {
	f1 := i.SubPrice1 * i.SubPrice2
	s := fmt.Sprintf("%.2f", v)
	f2, _ := strconv.ParseFloat(s, 64)
	i.Price = f2
	uadmin.Save(p)
}
```

**Comment by MarErm27** [comment]
> p.Cost

@alphakitchown may I ask, p.Cost is a string value?

**Comment by alphakitchown** [comment]
I used float64

**Comment by dxlvgcw** [comment]
@alphakitchown Your code works, but do you have to always depend on 2 decimal place value?

**Comment by alphakitchown** [comment]
My code is only just a sample. feel free to edit it for your need
