### ISSUE TITLE
Data Access API Read does not work in JS

### ISSUE THREAD

**Issue by alphakitchown** [uadmin/uadmin#56]
Greetings. I just want to say that Data Access API is one of the best feature ever so that I do not have to create an API file to access data. I accidentally found this from one of the closed issues. Fantastic!

http://localhost:8080/api/d lists all information related to Data Access API. I access http://localhost:8080/api/d/restaurant/read to read all Restaurant data.
```
{
  "result": [
    {
      "ID": 1,
      "DeletedAt": null,
      "Name": "Burger King",
      "Address": ""
    },
    {
      "ID": 2,
      "DeletedAt": null,
      "Name": "Domino's Pizza",
      "Address": ""
    },
    {
      "ID": 3,
      "DeletedAt": null,
      "Name": "Subway",
      "Address": ""
    },
    {
      "ID": 4,
      "DeletedAt": null,
      "Name": "Panda Express",
      "Address": ""
    }
  ],
  "status": "ok"
}
```

but performing in JS, i got this error
```
{
  "err_msg": "Permission denied",
  "status": "error"
}
```

Any advices please?

**Comment by dxlvgcw** [comment]
They really have this? Oh my gosh! I can't believe this! I spent all my life doing Golang JSONs whereas they prepared all of these automatic APIs for you.

**Comment by alphakitchown** [comment]
Yes! and i feel like i am in the weird side of uadmin to discover this feature.

**Comment by alphakitchown** [comment]
@dxlvgcw Can you do some scanning about this and figure out the solution to my problem?

**Comment by dxlvgcw** [comment]
Of course! You know my heart is palpitating right now from excitement.

**Comment by dxlvgcw** [comment]
I found the reason why. If your account is not logged in the uadmin page, you will get an error. That means you need to login your admin account first so that you can read data in JS.

**Comment by alphakitchown** [comment]
alright then. i think this is not good practice because if i publish my website, i have to let visitors to create an account for them to see model data. i know this is for security but, can we have something to break this barrier?

**Comment by dxlvgcw** [comment]
Hmmmm. We should ask for help.

**Comment by alphakitchown** [comment]
yes

**Comment by alphakitchown** [comment]
i will create my own API while waiting for the solution for the moment

**Comment by Spotlight64** [comment]
@alphakitchown Use APIPublicAdd model method. Return the value to true to enable public access. Place it below your type struct inside your model file. Instead of *Model, replace it with the name of your struct.
```
func (m *Model) APIPublicAdd(r *http.Request) bool {
    return true
}
```

**Comment by alphakitchown** [comment]
your the hero @Spotlight64

**Comment by MarErm27** [comment]
Hi!
May I ask for a link that tells how to use Data Access API?

**Comment by alphakitchown** [comment]
@MarErm27 Hi! I used https://github.com/uadmin/uadmin/issues/15 and http://localhost:8080/api/d for my references. its not yet available in read the docs so we have to manipulate them manually.

**Comment by dxlvgcw** [comment]
I just want to throw out the uadmin chart. There is full structure of Data Access API in the top left location.

https://coggle.it/diagram/XSzwl1j7lUdVWvIl/t/uadmin-the-golang-web-framework

**Comment by alphakitchown** [comment]
thank you @dxlvgcw. could be better if we have more examples than my references I have. i will leave more questions here
1. the use of join and how it works
2. how to use aggregation operators
3. the use of group by
4. the use of uadmin functions for data access api
5. m2m still not clear to me
6. apply public permission to all instead of letting me create function like APIPublicRead for every model
7. how prequery and postquery works and whats the difference between them
8. upload image and file attachment to model
9. data access api to send email
10. login and logout api is not listed in help
11. get data from a different database
12. show the total number of records in your model

**Comment by dxlvgcw** [comment]
I saw something like uadmin.PublicAdd and uadmin.PublicAdder like why did they have that?

**Comment by alphakitchown** [comment]
i dont even know. thats a mystery

**Comment by alphakitchown** [comment]
i know the point of PublicAdd but PublicAdder remains a mystery to me

**Comment by dxlvgcw** [comment]
There are so many questions to think about in the bigger picture. At least you discovered the secret treasure of uadmin.

**Comment by alphakitchown** [comment]
yes, it is an achievement that i even fell off my chair when i access this feature for the first time
