### ISSUE TITLE
Hello! May I ask you to help me find a remote job for writing programs in GO. Our organization sent all employees on vacation without payment. Please help

### ISSUE THREAD

**Issue by MarErm27** [uadmin/uadmin#57]
Hello!
May I ask you to help me find a remote job for writing programs in GO. Our organization sent all employees on vacation without payment. Please help

My last task was to create a Bid simulator for 44 Federal Law. There was going to be 40 auctions at same time and we needed to work out our groups actions. Each participant had to work with eight auctions at a time and send information of bidding process to the main manager. Main manager needed an analytics tool to make desigions. The task is not fully finished but we have already been doing trainings twice a week for last month. Please, check it out and help me to find a remote job. Thank you. Link : https://trade.3park.online/

Email: ErmMarat@gmail.com
Marat Ermeshev

**Comment by uadmin** [comment]
@MarErm27, you are one of the most active contributors and I would recommend you as developer or a team lead.

We should have a place where Golang and uAdmin developers can look for job opening in companies looking for good developers. We are a small community but we are growing really fast and it would be cool to have a our own job site.

https://twitter.com/twistedhardware/status/1246054986129330176
