### ISSUE TITLE
2-Factor image does not result in valid 2-factor codes generated

### ISSUE THREAD

**Issue by Giancarlos** [uadmin/uadmin#6]
I've tried to scan the QR code for 2-factor and the codes I get don't work, and do not match the log output. Is there something specific we have to configure to make sure 2-factor is correctly configured?

**Comment by rn1hd** [comment]
Can you check if the date/time on your PC is correctly configured?

**Comment by Spotlight64** [comment]
Thanks for your report. Can you please make sure if the date and time on your PC/Mobile device is set to current and let me know if this might solve your problem?

**Comment by Spotlight64** [comment]
All right. What really happens is after we enable the 2-Factor Auth in the profile page, the OTP image src in inspect did not change that causes the error.

Before
![Before](https://user-images.githubusercontent.com/49872771/57958153-64063e80-7931-11e9-90cf-73077b9d207f.png)

After
![After](https://user-images.githubusercontent.com/49872771/57958329-1e964100-7932-11e9-9a46-298c1e270d1a.png)

But if you refresh the page (Ctrl + F5), the OTP image src has changed.
![Result](https://user-images.githubusercontent.com/49872771/57958501-a11f0080-7932-11e9-82ae-a54ec98a6de0.png)

This is when the QR code for 2-factor will work. We will fix this feature for now and will push the bug fix on the next version.

Thanks for reporting.

**Comment by uadmin** [comment]
Fixed in 0.2.0 Just make sure you run `uadmin prepare` to get an updated copy of profile.html
