### ISSUE TITLE
$distinct for dAPI

### ISSUE THREAD

**Issue by Spotlight64** [uadmin/uadmin#61]
$distinct returns only distinct values and eliminates duplicate records from the results. It can be used in aggregation operators such as COUNT, AVG, MIN, MAX, etc.

$distinct has two values: 0 - false; 1 - true

Sample structure:
```
http://api.example.com/{ROOT_URL}/api/d/{MODEL_NAME}/read/?$f={FIELD_NAME}__count&$distinct={0,1}
```

Equivalent to SQL Command:
```
SELECT COUNT (DISTINCT field_name) FROM model_name
```

**Comment by MarErm27** [comment]
I've tried this
```
/admin/api/d/set/read/?$f=id__count&$distinct={0,1}
```
but it says

```
{
  "err_msg": "Unable to execute SQL. Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '`id) AS id__count FROM sets WHERE sets.deleted_at IS NULL' at line 1",
  "status": "error"
}
```

in MySQL
```
SELECT COUNT (DISTINCT id) FROM sets;
```
returns
```
12:45:27	SELECT COUNT (DISTINCT id) FROM sets	Error Code: 1064. You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DISTINCT id) FROM sets' at line 1	0.000 sec
```

But this in MySQL
```
SELECT COUNT(DISTINCT(id)) FROM sets;
```
returns number of unique entities in table "sets"



so instead of this for MySQL
```
SELECT COUNT (DISTINCT field_name) FROM model_name
```
it needs to be like this
```
SELECT COUNT(DISTINCT(field_name)) FROM model_name
```

**Comment by Spotlight64** [comment]
Thank you for the correction on the format for MySQL. DISTINCT is not yet implemented inside dAPI. That is our plan for the next update.

**Comment by MarErm27** [comment]
> 
> 
> Thank you for the correction on the format for MySQL. DISTINCT is not yet implemented inside dAPI. That is our plan for the next update.

Can I be helpful on your team?

**Comment by Spotlight64** [comment]
Sure! I really appreciate that.
@uadmin 
@TwistedHardware 
@jmsemira
@rmarasigan

**Comment by MarErm27** [comment]
> 
> 
> Sure! I really appreciate that.
> @uadmin
> @TwistedHardware
> @jmsemira
> @rmarasigan

May you give me a task?

**Comment by dxlvgcw** [comment]
Great concept. I also would like to join too.

**Comment by Spotlight64** [comment]
Ok. There's one issue that I still need to solve in the docs project that is the FAQ section. More details here:
https://github.com/uadmin/uadmin/issues/44

This is our repo for the uadmin docs. You may clone the repo here then you can start working on the FAQ. Once you are done, create a pull request then I'll add you to the contributors.
https://github.com/uadmin/uadmin-docs

**Comment by Spotlight64** [comment]
Other things that we need to work on is the website. https://uadmin.io/

**Comment by dxlvgcw** [comment]
After I check the website, I have to change my mind. I think it is better to place the FAQ in the website.

**Comment by Spotlight64** [comment]
noted

**Comment by dxlvgcw** [comment]
@MarErm27 Who will take the website? You or me?

**Comment by MarErm27** [comment]
> 
> 
> @MarErm27 Who will take the website? You or me?

Can we do it together?
![image](https://user-images.githubusercontent.com/56219126/85921324-3a358000-b884-11ea-8f42-c4e245bce061.png)
I think here we need to add a link to Documentation
What to do next?

**Comment by dxlvgcw** [comment]
I think it would be better to wait the repo admin about the plans of the website since I am not a part of their team. We also do not have the download links that we can store in the download page. The documentation link can be a web page.

**Comment by dxlvgcw** [comment]
Once the admin posted the plans of the website, then we can start working together.

**Comment by MarErm27** [comment]
> 
> 
> Once the admin posted the plans of the website, then we can start working together.

Looking forward to start

**Comment by TwistedHardware** [comment]
How about you add the column name to $distinct as a value I stead of 0,1:
`http://api.example.com/{ROOT_URL}/api/d/{MODEL_NAME}/read/?$f={FIELD_NAME}__count&$distinct={FIELD_NAME}__count`

This way you can actually specify which column you want to use for your distinct.

**Comment by Spotlight64** [comment]
I read an article about DISTINCT https://www.db2tutorial.com/db2-basics/db2-select-distinct/

According to the article:
```
The DISTINCT keyword is applied to all columns. It means that the query will use the combination of values in all columns to evaluate the distinction.

If you want to select distinct values of some columns in the select list, you should use the GROUP BY clause.
```

I support the idea of specifying which column you want to use for your distinct. In this case, the $f calls will be ignored. If we need to care the $f, we can stick to a boolean value for the $distinct. There are two options.

**Comment by Spotlight64** [comment]
@MarErm27 @dxlvgcw I appreciate your participation and willingness to implement the uAdmin website. Look forward to our owner's announcement then he will provide the information you need for the website. Thank you guys.

**Comment by dxlvgcw** [comment]
@Spotlight64 I just want to share my point on your distinct plan. Although it sounds impossible to communicate between $f and $distinct, you may create an exception handling to say unable to execute SQL command, something like that.

**Comment by Spotlight64** [comment]
You are right. Maybe the dAPI response can throw this JSON error like this:
```
{
    "status": "error",
    "err_msg": "Cannot execute $f and $distinct at the same time"
}
```

**Comment by Spotlight64** [comment]
I have a way to execute $f and $distinct at the same time. I'll check if the values of those special parameters are the same.
```
http://api.example.com/{ROOT_URL}/api/d/{MODEL_NAME}/read/?$f=name,age&$distinct=name,age
```

Otherwise, it will throw a JSON error as shown above this comment. This API call might be a tedious task to the user in fact that they have to ensure the similarity between $f and $distinct.

**Comment by dxlvgcw** [comment]
How about __distinct?

**Comment by Spotlight64** [comment]
It will not work. DISTINCT applies to all columns. If you want to select distinct values of some columns in the select list, you will use $groupby.

**Comment by dxlvgcw** [comment]
What is your final pick?

**Comment by Spotlight64** [comment]
My best personal choice would be your suggestion. Put $distinct as the most priority and throw a JSON error if you execute both $f and $distinct at the same time. I need to discuss this with the team so we can have a final plan about this feature. Thank you for your participation on this plan.

**Comment by dxlvgcw** [comment]
No problem. Glad I can help on your team

**Comment by dxlvgcw** [comment]
@Spotlight64 Please release a new tag for uadmin because we cannot use some of the new features. We cannot afford to downgrade our version of Go in order to import your latest uadmin project.

**Comment by uadmin** [comment]
OK, this is already implemented in the new version 0.5.0 as `$distinct=1` to apply distinct to your dAPI request. The release date will be August 1st. Sorry for the delay and hope it will help your projects.

**Comment by Spotlight64** [comment]
Good day guys! Whenever you have issues, concerns, or plans that you want to share, join here in Gophers Slack https://gophers.slack.com/join/shared_invite/zt-fajz7jh3-2cpkmFU~hQb8d5LmOCnhfQ#/ then join #uadmin channel. Let's work together!

**Comment by uadmin** [comment]
Fixed in https://github.com/uadmin/uadmin/releases/tag/v0.5.0
