### ISSUE TITLE
Release a new version tag (Go Users > 1.12)

### ISSUE THREAD

**Issue by dxlvgcw** [uadmin/uadmin#62]
Please release a new tag for uadmin because we cannot use some of the new features. We cannot afford to downgrade our version of Go in order to import your latest uadmin project.

FYI, Go users with version greater than 1.12 has imported the library directly from https://pkg.go.dev/github.com/uadmin/uadmin?tab=doc

**Comment by Spotlight64** [comment]
Sure! We'll create a new tag for you on the next update. Thank you for reminding us about the issue.

**Comment by uadmin** [comment]
The new release (0.5.0) will be on August 1st. We will be more active in changing the last number in the version going forward. Thanks for the heads up.

**Comment by uadmin** [comment]
Fixed in https://github.com/uadmin/uadmin/releases/tag/v0.5.0
