### ISSUE TITLE
Hide In Dashboard not working

### ISSUE THREAD

**Issue by madong17** [uadmin/uadmin#65]
I follow the final part of document system tutorial in https://uadmin-docs.readthedocs.io/en/latest/document_system/tutorial/part17.html. The model is not hiding in my dashboard. Can you tell me what I miss something?

**Comment by Spotlight64** [comment]
I've tested it just now and have the same issue. Thanks for reporting.

**Comment by Spotlight64** [comment]
Good day! If the model is already added, you cannot hide it. You should hide it before you synch the database the first time.

We'll try to make it hide the model even after it is already added then we'll let you know the update about this. Thanks for reporting.

**Comment by madong17** [comment]
Thanks for your response @Spotlight64

**Comment by uadmin** [comment]
In the next version `0.5.0` models will be hidden even after adding them. The release date will be August 1st. Thanks for reporting and hope you will find the new version more helpful in your project.

**Comment by madong17** [comment]
Great! I am excited on the next version.

**Comment by uadmin** [comment]
Fixed in https://github.com/uadmin/uadmin/releases/tag/v0.5.0
