### ISSUE TITLE
New website

### ISSUE THREAD

**Issue by uadmin** [uadmin/uadmin#66]
The current website for uadmin.io sucks! I would love to work on a new website for uAdmin but I have so much on my plate with the development of uAdmin and my work. I created a new repo for the website:

https://github.com/uadmin/uadmin.github.io

If you are interested in making a website for uAdmin, I'll give you control over that repo and it will be collaboration effort. We have some people who can help:
@Spotlight64
Harold (I don't know his user name in Github)

Please let me know if you can help and let's discuss a a working team for this website.

**Comment by Spotlight64** [comment]
Harold's Github name is @haroldjeshua. I'm willing to take that one once I get a few plate on my work. There are two members I've talked before who are also willing to work on the uadmin website as well discussed in https://github.com/uadmin/uadmin/issues/61

**Comment by davidhtims** [comment]
I can help.
I like simple and would shy away from a big framework - but could be persuaded otherwise ...

**Comment by TwistedHardware** [comment]
This has been stale for a long time. I think it's time we make uadmin.io point to the docs
