### ISSUE TITLE
Filter not working.

### ISSUE THREAD

**Issue by Giancarlos** [uadmin/uadmin#7]
I'm not sure what I have to do to get filter working, but I type anything in after I click Filter, then click Filter in the modal and nothing happens.

**Comment by freeairy** [comment]
I'm use same filter not working,
and use uAdmin Tutorial Part 3 - Linking Models¶method sort , filter not working.

**Comment by dxlvgcw** [comment]
You have to put filter tag at the end of the field inside the struct. It applies with data types such as string and int. https://uadmin.readthedocs.io/en/latest/tags.html#filter

**Comment by dxlvgcw** [comment]
It seems that filter does not work in foreign key fields but it works with the string data type fields. I think filter is searching based on where you put the filter tag.

Here is my code:
type Device struct {
&nbsp;&nbsp;uadmin.Model
&nbsp;&nbsp;Name string `uadmin:"filter"`
&nbsp;&nbsp;Description string
}

Filter works based on the name. I searched based on the description then nothing happens.

**Comment by freeairy** [comment]
I understand，thx ^ ^

**Comment by Spotlight64** [comment]
Recently found out why Filter did not work based on this result in the terminal:

[  ERROR ]   DB error in AdminPage(). no such column: name__contains

[35m(no such column: name__contains)[0m
[33m[2019-05-26 17:09:01][0m [31;1m [0m

[35m(no such column: name__contains)[0m
[33m[2019-05-26 17:09:01][0m [31;1m [0m
[  ERROR ]   DB error in Count(). no such column: name__contains

We will fix this feature for now and will push the bug fix on the next version.

Thanks for reporting.

**Comment by uadmin** [comment]
Fixed in 0.3.0
