### ISSUE TITLE
dAPI to change the settings

### ISSUE THREAD

**Issue by nrdh3g** [uadmin/uadmin#70]
I am one of the loyal user of your framework. Would you rather add dAPI implementation to change the settings, something like
uadmin.Port >> ?port=1234
uadmin.RootURL >> ?rooturl=adminroot

Waiting for your response

**Comment by TwistedHardware** [comment]
sorry for the late reply. You can already do that.

`/api/d/edit?code=uAdmin.Port&_value=1234`

Don't forget that settings are just records in a model and you can read, edit, delete them from dAPI like everything else :)
