### ISSUE TITLE
Uadmin improvements, refactoring, decouple bussiness logic into separated blueprints

### ISSUE THREAD

**Issue by sergeyglazyrindev** [uadmin/uadmin#72]
Hello guys!
I am working now on refactoring uadmin, it's not ready yet, it's only WIP. But I think I made some progress.
So, the idea is to make uadmin easily customizable, easily usable with good test coverage, with ability to use different databases without writing if/else in the code.
All my work is here: https://github.com/sergeyglazyrindev/uadmin
So, made some progress:
1. added easy way to write a command for uadmin project: for example, this command starts swagger server with api spec of the current project: https://github.com/sergeyglazyrindev/uadmin/blob/master/swagger.go
2. added migrations command to uadmin. It supports up/down/create and support multiple dependencies for each migration. Example here: https://github.com/sergeyglazyrindev/uadmin/blob/master/migrate.go and here is a concrete migration: https://github.com/sergeyglazyrindev/uadmin/blob/master/blueprint/user/migrations/initial_1621680132.go
3. added command blueprint to create new blueprint: https://github.com/sergeyglazyrindev/uadmin/blob/master/blueprint.go
4. added dialect https://github.com/sergeyglazyrindev/uadmin/tree/master/dialect that could be used with different databases. It helps us to keep database specific details in a separated go folder. It has to be improved, there are few things that I didn't improve
5. added project config: https://github.com/sergeyglazyrindev/uadmin/blob/master/config/config.go which contains all data needed for project, it helps us to start uadmin in different environments.,
6. each blueprint has own routing group.

Next improvements are:
1. redesign current implementation of REST logic for api requests in uadmin to use proper http methods and keep code as much explicit as possible, reflect is a great power but it makes code hard to understand, etc.....
2. start uadmin admin panel, and then step by step start using new http blueprint methodology for all blueprints and finally get uadmin working as right now. with almost all features currently existing in uadmin

Anyone welcome to review, suggest something, take a part in the improving uadmin.

**Comment by MarErm27** [comment]
Hello!
Thank you for sharing!
I was wondering if I may ask what is blueprints for bussiness logic?

**Comment by sergeyglazyrindev** [comment]
hey @MarErm27 
Blueprint basically is a synonym to new bussiness feature. It has to contain all bussiness logic related to the same part of bussiness logic.
I love how it is implemented in flask.
You can read this link: https://flask.palletsprojects.com/en/2.0.x/blueprints/
You can understand it more if you watch this video: https://www.youtube.com/watch?v=MYYd4sImfmI and https://python.plainenglish.io/python-web-development-with-flask-blueprints-and-commands-1cb1986271b
