### ISSUE TITLE
[CRITICAL]   Request failed Anti-CSRF protection from user:admin IP:::1

### ISSUE THREAD

**Issue by MarErm27** [uadmin/uadmin#73]
Hello!

When I try to add new user I got the error in the tittle. Also when I try to change any field in existing models with the Uadmin interface I got the same error. The page dispays 404. I was wondering if you may suggest how to fix it? Thank you

The browser is Google Chrome. 
Uadmin version is github.com/uadmin/uadmin v0.5.2

**Comment by sergeyglazyrindev** [comment]
Hey, could you please attach headers sent with your request to server.... ?

**Comment by Spotlight64** [comment]
Hi, there are two reasons why error happens:

1.) You might be installed the latest version of uadmin and the uadmin files stored on your project folder is outdated.

Example:
```
uadmin version
[INFO] 0.6.2
```

While the uadmin files stored on your project is 0.5.2. In this case, you need to do **uadmin prepare --src** in your terminal to update static and templates files on your project.

2.) If Solution #1 did not solve the problem, there is something to do with the Golang version installed on your computer. We have encountered some issues in uadmin, although not the same issue as this, when we try to access admin dashboard that does not display anything and applying m2m field that does not work also. The Golang version we've installed is 1.15.X so we attempted to update Go to 1.16. After updating Go to 1.16, our issues in uadmin has been resolved.

**Comment by MarErm27** [comment]
> Hey, could you please attach headers sent with your request to server.... ?
Hello! 

Headers:
```
Request URL: http://localhost:3000/static/uadmin/js/notify.min.js?_=1624256459918
Request Method: GET
Status Code: 200 OK
Remote Address: [::1]:3000
Referrer Policy: strict-origin-when-cross-origin
Accept-Ranges: bytes
Cache-Control: private, max-age=3600
Content-Length: 13782
Content-Type: text/plain; charset=utf-8
Date: Mon, 21 Jun 2021 06:20:59 GMT
Last-Modified: Tue, 02 Mar 2021 10:25:36 GMT
Accept: text/javascript, application/javascript, application/ecmascript, application/x-ecmascript, */*; q=0.01
Accept-Encoding: gzip, deflate, br
Accept-Language: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7
Connection: keep-alive
Cookie: language=en; session=_6H6ikEwqpZfRnhc1T0wdo7m; abt=26
Host: localhost:3000
Referer: http://localhost:3000/admin/user/new
sec-ch-ua: " Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"
sec-ch-ua-mobile: ?0
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36
X-Requested-With: XMLHttpRequest
_: 1624256459918
```

**Comment by MarErm27** [comment]
@Spotlight64 
It's all works now, thank you.

I've updated the UAdmin from 5.2 to 6.2 with this command ```go get -u -v github.com/uadmin/uadmin/...```


I've tried to ```uadmin prepare --src```, but
```
[  INFO  ]   Copying static/templates from: C:\Users\Marat\go\src\github.com\uadmin\uadmin
[ WARNING]   Unable to copy "static" folder: CreateFile C:\Users\Marat\go\src\github.com\uadmin\uadmin\static: The system cannot find the path specified.
[ WARNING]   Unable to copy "templates" folder: CreateFile C:\Users\Marat\go\src\github.com\uadmin\uadmin\templates: The system cannot find the path specified.
```
there are no UAdmin folder in src folder.

so I've tried ```uadmin prepare``` instead and:
```
[  INFO  ]   Copying static/templates from: C:\Users\Marat\go\pkg\mod\github.com\uadmin\uadmin@vv0.6.2
[ WARNING]   Unable to copy "static" folder: CreateFile C:\Users\Marat\go\pkg\mod\github.com\uadmin\uadmin@vv0.6.2\static: The system cannot find the path specified.
[ WARNING]   Unable to copy "templates" folder: CreateFile C:\Users\Marat\go\pkg\mod\github.com\uadmin\uadmin@vv0.6.2\templates: The system cannot find the path specified.
```

folder uadmin@v0.6.2 exist on this path, but uadmin@vv0.6.2 don't. I've renamed uadmin@v0.6.2 to v and:
```
[  INFO  ]   Copying static/templates from: C:\Users\Marat\go\pkg\mod\github.com\uadmin\uadmin@vv0.6.2
[   OK   ]   Updated: C:\GoModules\trade\static
[   OK   ]   Updated: C:\GoModules\trade\templates
```

Thank you @sergeyglazyrindev and @Spotlight64 for your help!
