### ISSUE TITLE
APIPreQueryRead double execution is a bug ?

### ISSUE THREAD

**Issue by ngmedina14** [uadmin/uadmin#75]
I tried to make it very simple test for APIPreQueryRead. I think there is a bug in the process.

Test it yourself. Make a **simple model** with APIPreQueryRead and APIPostQueryRead inside. Let say **Item.go**

```
type Item struct {
	uadmin.Model
	Name        string
	Description string
	Price       int
}

// Return the value to true to enable pre query access to read method
func (Item) APIPreQueryRead(w http.ResponseWriter, r *http.Request) bool {
	fmt.Println("Pre Query Read")
	return true
}

// Return the value to true to enable post query access to read method
func (Item) APIPostQueryRead(w http.ResponseWriter, r *http.Request, res map[string]interface{}) bool {
	fmt.Println("Post Query Read")
	return true
}
```

After that **Execute a simple dAPI.** Like this
`http://localhost:8080/admin/api/d/item/read`

and from the Terminal, I got this result.
```go build; ./dapitest
[   OK   ]   Initializing DB: [14/14]
[   OK   ]   Synching System Settings: [51/51]
[   OK   ]   Server Started: http://0.0.0.0:8080
         ___       __          _
  __  __/   | ____/ /___ ___  (_)___
 / / / / /| |/ __  / __ '__ \/ / __ \
/ /_/ / ___ / /_/ / / / / / / / / / /
\__,_/_/  |_\__,_/_/ /_/ /_/_/_/ /_/

Pre Query Read
Pre Query Read
Post Query Read
```

I think APIPreQueryRead is not suppose to be executed 2 times? But I can utilize the APIPostQueryRead instead and make the APIPreQueryRead for authentication only. But still I think APIPreQueryRead should be executed one time so we can maximize the usage of it.

**Comment by dxlvgcw** [comment]
agree with this.. this needs to be fixed

**Comment by madong17** [comment]
Tested in all different angles. I can confirm that pre queries are bugs. It is not supposed to be like that.
