### ISSUE TITLE
Export to Excel not working

### ISSUE THREAD

**Issue by Giancarlos** [uadmin/uadmin#8]
I'm not seeing any obvious indication of why I'm getting a 404, I would assume this button not even show up if it doesn't function. There's likely something I'm missing though.

**Comment by dxlvgcw** [comment]
I think export supports only with non-pointer data types in fields. I have tried implementing the model with a pointer data type and I get the same error.

type Folder struct {
    uadmin.Model
    Name     string
    **Parent   *Folder**
    ParentID uint
}
