### ISSUE TITLE
Could not install uadmin

### ISSUE THREAD

**Issue by linuxluigi** [uadmin/uadmin#81]
Hey, I recently found your project & I was really happy to see what you did ❤️ It just looks awesome 🤩

But when I tried to install `uAdmin` I've got the following error:
```bash
❯ go get -u github.com/uadmin/uadmin/...
go: downloading golang.org/x/crypto v0.0.0-20210920023735-84f357641f63
go get: github.com/360EntSecGroup-Skylar/excelize/v2@v2.4.1: parsing go.mod:
	module declares its path as: github.com/xuri/excelize/v2
	        but was required as: github.com/360EntSecGroup-Skylar/excelize/v2
```

**Comment by Spotlight64** [comment]
Good day! Thanks for reaching out. We are informed about the issue and the cause of it is that the Excelize import is already outdated. For now, you can try to install `uAdmin` without depending on the Go modules while the fix is still ongoing. Hope it helps!

**Comment by linuxluigi** [comment]
Thanks for you Info 🙂
I will check it out.
