### ISSUE TITLE
dAPI Edit command returns 0 rows count

### ISSUE THREAD

**Issue by rn1hd** [uadmin/uadmin#83]
![Untitled](https://user-images.githubusercontent.com/49872771/134096832-ceb1e9b6-aa0a-42a6-b1c1-92bc57d9707c.png)

dAPI Query Sample: http://api.example.com/{ROOT_URL}/api/d/item/edit/?rating=4&_rating=5&x-csrf-token={YOUR_SESSION_KEY}

```json
{
    "rows_count": 0,
    "status": "ok"
}
```

![Untitled](https://user-images.githubusercontent.com/49872771/134096854-a5ff2940-5bf3-41b1-a80b-38f4f2c0568f.png)

dAPI edit works technically but it returns 0 rows count affected in the result object.

**Comment by TwistedHardware** [comment]
Than you for the report.

I'll look into it right now, hopefully it will be in the next release in a few days.

**Comment by TwistedHardware** [comment]
Fixed in [fd8371a](https://github.com/uadmin/uadmin/commit/fd8371aeaf31ac1ac804bc785bc965218b634b4d)
