### ISSUE TITLE
Built-in User and Group Permissions are not working

### ISSUE THREAD

**Issue by rn1hd** [uadmin/uadmin#84]
I ensure that the second account is not an Admin.

![Untitled](https://user-images.githubusercontent.com/49872771/134097163-f283b782-44ba-4036-850a-ab8e98ef62a2.png)

I set the read user permission that links to the Todo model.

![Untitled](https://user-images.githubusercontent.com/49872771/134097188-4b7248b3-a85e-4286-8ca4-1565f657d13c.png)

I tried to login a non-admin account. Only the Todo model has displayed in the uAdmin dashboard because that's the only model I have access permission to.

![Untitled](https://user-images.githubusercontent.com/49872771/134097278-4df511b4-771a-4d26-a39e-deb028fa0158.png)

After I click TODOS in the dashboard, it returns 404 Page Not Found

![Untitled](https://user-images.githubusercontent.com/49872771/134097386-2f0563bd-8a5d-4a08-990b-936a9219a2d4.png)

Similar issue goes to Group Permissions.

**Comment by TwistedHardware** [comment]
The default for permission is cached permission. From settings, change cached permission to false or just restart your application and the new permissions will be loaded.
