### ISSUE TITLE
Dockerized application issues

### ISSUE THREAD

**Issue by maitredede** [uadmin/uadmin#87]
Hello,

The docs and the readme lacks the docker part. Can I suggest a sample Dockerfile for tutorial application ?

```Dockerfile
FROM golang:1.17-alpine AS build-go
RUN set -ex ;\
    apk upgrade --no-cache --available ;\
    apk add --no-cache build-base
WORKDIR /src
ARG GOPROXY
ARG GONOSUMDB
ARG GOPRIVATE
RUN go install github.com/uadmin/uadmin/cmd/uadmin@latest
ADD go.mod go.sum ./
RUN go mod download
ADD . ./
RUN go generate ./...
RUN go vet ./...
RUN go install ./...

FROM alpine:edge
RUN set -ex ;\
    apk upgrade --no-cache --available ;\
    apk add --no-cache tzdata rrdtool
WORKDIR /app
COPY --from=build-go /go/bin/eval-uadmin /app/bin
COPY --from=build-go /src/templates/ /app/templates/
COPY --from=build-go /src/static/ /app/static/
ENTRYPOINT [ "/app/bin" ]
```

I have issues with logging :
```
[  ERROR ]   Hanlder.NewLogger. Unix syslog delivery error
```

**Comment by dxlvgcw** [comment]
I noticed that too like a month ago that something is lacking, finally I am not the only person. Unfortunately, I have not touch Docker yet so I cannot help. I believe the uadmin team is working on it for the next version maybe?

**Comment by alphakitchown** [comment]
The Docker procedure is already floating long time ago in the docs. I was surprised that it is published there but I would agree that the team might still developing it as future feature. Let us wait and see.

**Comment by dxlvgcw** [comment]
Owww really??????? When did you know it @alphakitchown

**Comment by alphakitchown** [comment]
Since August. I was about to initiate an issue during that time. However, I decided to keep my mouth shut for now and wait for the uadmin development team to release an update. I have no idea what version number they will put if it is 0.6.3 or something.

**Comment by dxlvgcw** [comment]
If the team still don't provide sample for Docker after they release an update, what does that mean in your opinion?

**Comment by alphakitchown** [comment]
I do not jump into conclusions. The best thing we can do is to wait for the uadmin development team to release an announcement regarding this Docker issue.

**Comment by dxlvgcw** [comment]
Why do not we try to solve the issue ourselves @alphakitchown

**Comment by alphakitchown** [comment]
I tried. It is a flop.

**Comment by dxlvgcw** [comment]
Then you should address them on that time. Why did you choose to wait?

**Comment by alphakitchown** [comment]
It is because I have other alternatives to achieve the same target.

**Comment by Gaurav-Gosain** [comment]
I've got the
```
[  ERROR ]   Hanlder.NewLogger. Unix syslog delivery error
```
issue as well when working with a dockerized uAdmin instance. Hopefully someone more experienced with docker/uAdmin can help us out here!

**Comment by TwistedHardware** [comment]
Fixed in the master. Will be leased in v0.9.0
