### ISSUE TITLE
Oauth authentication

### ISSUE THREAD

**Issue by maitredede** [uadmin/uadmin#98]
Hello,
I would like to provide oauth authentication (Keycloak, facebook, google, gitlab, github...), with configurable account merge/association policy.

**Comment by TwistedHardware** [comment]
That is a great idea that I had in mind for a long time. I'll look into adding a handler for oAuth 2.0 in the next release 0.10 (maybe?)

**Comment by TwistedHardware** [comment]
uAdmin now supports JWT authentication which is a good first step in getting oAuth 2.0 implementation ready for next major release.
[Add JWT access support](https://github.com/uadmin/uadmin/commit/bcab92da407ce74ea4b76e1d978669916ded6c1d)
